    ---
    - name: "U-63 | Remediate sudoers owner/permission (Controlled Env, Logs-Only JSONL)"
      hosts: all
      become: yes
      gather_facts: no
    
      vars:
        FLAG_ID: "U-63"
    
        # ===== 팀 로그 템플릿(고정) =====
        LOG_SECTION_STEP: "[조치 내용]"
        LOG_SECTION_BASIS: "[조치 결과]"
        LOG_TITLE_BASIS: "조치 근거"
        LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"
    
        # ===== 조치 값(고정) =====
        SUDOERS_PATH: "/etc/sudoers"
        AUTO_OWNER: "root"
        AUTO_GROUP: "root"
        AUTO_MODE: "0640"
    
      tasks:
        # ---------------------------------------------------------
        # (공통) 미정의 방지
        # ---------------------------------------------------------
        - name: "U-63 | init defaults"
          ansible.builtin.set_fact:
            has_sudo_pkg: "UNKNOWN"     # YES/NO/UNKNOWN
            st_sudoers: { stat: { exists: false } }
            r_u631: {}
          changed_when: false
    
        # ---------------------------------------------------------
        # sudo 패키지 설치 여부(best-effort)
        # - 통제 환경이지만, sudo 미설치면 sudoers 미사용 케이스가 있으므로
        #   '통칭 info'가 아니라 '구체 사유 info'를 남기기 위한 용도
        # ---------------------------------------------------------
        - name: "U-63 | detect sudo package (rpm/dpkg best-effort)"
          ansible.builtin.shell: |
            set -o pipefail
            if command -v rpm >/dev/null 2>&1; then
              rpm -qa | grep -qiE "^sudo-" && echo "YES" || echo "NO"
            elif command -v dpkg-query >/dev/null 2>&1; then
              dpkg-query -W -f='${Package}\n' 2>/dev/null | grep -qiE "^sudo$" && echo "YES" || echo "NO"
            else
              echo "UNKNOWN"
            fi
          args:
            executable: /bin/bash
          register: r_sudo_pkg
          changed_when: false
          failed_when: false
    
        - name: "U-63 | set has_sudo_pkg"
          ansible.builtin.set_fact:
            has_sudo_pkg: "{{ r_sudo_pkg.stdout | default('UNKNOWN') }}"
          changed_when: false
    
        # ---------------------------------------------------------
        # U_63_1 : /etc/sudoers 소유자/권한(root:root,0640) 조치
        # - 파일이 없으면 자동조치 불가(info)로 기록
        # ---------------------------------------------------------
        - name: "U-63 | [U_63_1] stat /etc/sudoers"
          ansible.builtin.stat:
            path: "{{ SUDOERS_PATH }}"
          register: st_sudoers
          changed_when: false
    
        - name: "U-63 | [U_63_1] ts (existence)"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_631_a
          changed_when: false
    
        - name: "U-63 | [U_63_1] LOG step (sudoers existence) JSONL"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_631_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_63_1] /etc/sudoers 파일 존재 여부",
                  "cmd": "[ -f " ~ SUDOERS_PATH ~ " ]",
                  "result": ((st_sudoers.stat.exists | default(false)) | ternary("파일 존재","파일 없음"))
                } | to_json
              }}
          changed_when: false
    
        - name: "U-63 | [U_63_1] enforce owner/mode"
          ansible.builtin.file:
            path: "{{ SUDOERS_PATH }}"
            owner: "{{ AUTO_OWNER }}"
            group: "{{ AUTO_GROUP }}"
            mode: "{{ AUTO_MODE }}"
          register: r_u631
          when: st_sudoers.stat.exists | default(false)
    
        - name: "U-63 | [U_63_1] LOG step+basis (applied) JSONL"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_631_b
              changed_when: false
    
            - name: "LOG step"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_631_b.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_STEP,
                      "title": "[U_63_1] /etc/sudoers 소유자/권한(root:root,0640) 조치",
                      "cmd": "file: owner=root group=root mode=0640 @ " ~ SUDOERS_PATH,
                      "result": "changed=" ~ (((r_u631.changed | default(false)) | bool) | string)
                    } | to_json
                  }}
              changed_when: false
    
            - name: "LOG basis"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_631_b.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_BASIS,
                      "title": LOG_TITLE_BASIS,
                      "basis": "[U_63_1] sudoers 파일(" ~ SUDOERS_PATH ~ ") 소유자/권한을 root:root,0640 으로 설정(비인가 수정 방지) — 기준: 0640 이하",
                      "status": (((r_u631.changed | default(false)) | bool) | ternary("취약","양호"))
                    } | to_json
                  }}
              changed_when: false
          when: st_sudoers.stat.exists | default(false)
    
        - name: "U-63 | [U_63_1] LOG basis (auto not possible) JSONL"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_631_na
              changed_when: false
    
            - name: "LOG basis"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_631_na.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_BASIS,
                      "title": LOG_TITLE_BASIS,
                      "basis": (
                        (has_sudo_pkg == "NO")
                        | ternary(
                            "[U_63_1] sudo 패키지 미설치로 sudoers(" ~ SUDOERS_PATH ~ ") 미사용/미존재 케이스 — 권한 조치 대상 없음(info)",
                            "[U_63_1] sudoers 파일(" ~ SUDOERS_PATH ~ ") 미존재로 소유자/권한 조치 불가(info) — 표준 경로/배포 정책 확인 필요"
                          )
                      ),
                      "status": "info"
                    } | to_json
                  }}
              changed_when: false
          when: not (st_sudoers.stat.exists | default(false))