---
- name: "U-20 /etc/xinetd.conf 및 관련 파일 권한 설정"
  hosts: all
  become: yes
  vars:
   flag_list: 
    - U_20_1
    - U_20_2
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/ubuntu24-remediate_{{ flag_list }}.log"
   my_json_file: "{{ json_dir }}/ubuntu24-remediate_{{ flag_list }}.json"
  tasks: 

    # 1. /etc/inetd.conf 체크
    - name: "inetd.conf 파일 정보 확인"
      ansible.builtin.stat:
        path: "/etc/inetd.conf"
      register: inetd_stat
      when: "'U_20_1' in flag_list"

    - name: "inetd.conf 권한 설정"
      ansible.builtin.file:
        path: "/etc/inetd.conf"
        owner: root
        group: root
        mode: '0600'
      # 문법 수정: '=' 대신 '==' 사용, '&&' 대신 'and' 사용
      when: 
        - inetd_stat.stat.exists
        - "'U_20_1' in flag_list"
        
    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_20_1",
          "section": "[조치 내용]",
          "title": "[U_20_1] (inetd.conf 권한 설정)",
          "cmd": " chown root /etc/inetd.conf, chmod 600 /etc/inetd.conf",
          "result": "조치 성공 (inetd.conf 권한 설정)"
         } | to_json
        }}
      when: "'U_20_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_20_1",
              "status": 2, 
              "description": "inetd.conf 권한 설정 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_20_1' in flag_list"

    # 2. xinetd 관련 설정 체크
    - name: "xinetd.d 디렉터리 존재 여부 확인"
      ansible.builtin.stat:
        path: "/etc/xinetd.d"
      register: xinetd_dir_stat
      when: "'U_20_2' in flag_list"

    - name: "xinetd 관련 파일 목록 검색"
      ansible.builtin.find:
        paths: ["/etc/xinetd.d"]
        patterns: "*"
      register: xinetd_files
      when: 
       - xinetd_dir_stat.stat.isdir is defined and xinetd_dir_stat.stat.isdir
       - "'U_20_2' in flag_list"

    - name: "xinetd.conf 파일 정보 확인"
      ansible.builtin.stat:
        path: "/etc/xinetd.conf"
      register: xinetd_conf_stat
      when: "'U_20_2' in flag_list"

    - name: "xinetd.conf 및 하위 파일 권한 설정"
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: '0600'
        state: file
      # 검색된 파일 리스트와 단일 파일을 합치되, 실제 존재하는 것만 필터링
      loop: >-
        {{ (xinetd_files.files | default([]) | map(attribute='path') | list) + 
           (['/etc/xinetd.conf'] if xinetd_conf_stat.stat.exists else []) }}
      when: 
       - item is defined
       - "'U_20_2' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_20_2",
          "section": "[조치 내용]",
          "title": "[U_20_2] (xinetd.conf 권한 설정)",
          "cmd": "chmod 600 /etc/xinet.conf, chown root /etc/xinetd.conf",
          "result": "조치 성공 (xinetd.conf 및 하위 폴더 권한 설정)"
         } | to_json
        }}
      when: "'U_20_2' in flag_list" 

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_20_2",
          "section": "[조치 내용]",
          "title": "[U_20_2] (xinetd.conf 하위 폴더 권한 설정)",
          "cmd": "chmod 600 /etc/xinet.d/, chown -R root /etc/xinetd.d/",
          "result": "조치 성공 (xinetd.conf 및 하위 폴더 권한 설정)"
         } | to_json
        }}
      when: "'U_20_2' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_20_2",
              "status": 2, 
              "description": "xinetd.conf 및 하위 파일 권한 설정 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_20_2' in flag_list"

    # 2. systemd 관련 설정 체크
    - name: "systemd 디렉터리 존재 여부 확인"
      ansible.builtin.stat:
        path: "/etc/systemd.d"
      register: systemd_dir_stat
      when: "'U_20_3' in flag_list"

    - name: "systemd 관련 파일 목록 검색"
      ansible.builtin.find:
        paths: ["/etc/systemd.d"]
        patterns: "*"
      register: systemd_files
      when: 
       - systemd_dir_stat.stat.isdir is defined and systemd_dir_stat.stat.isdir
       - "'U_20_2' in flag_list"

    - name: "systemd.conf 파일 정보 확인"
      ansible.builtin.stat:
        path: "/etc/systemd.conf"
      register: systemd_conf_stat
      when: "'U_20_2' in flag_list"

    - name: "systemd.conf 및 하위 파일 권한 설정"
      ansible.builtin.file:
        path: "{{ item }}"
        owner: root
        group: root
        mode: '0600'
        state: file
      # 검색된 파일 리스트와 단일 파일을 합치되, 실제 존재하는 것만 필터링
      loop: >-
        {{ (systemd_files.files | default([]) | map(attribute='path') | list) + 
           (['/etc/systemd.conf'] if systemd_conf_stat.stat.exists else []) }}
      when: 
       - item is defined
       - "'U_20_3' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_20_3",
          "section": "[조치 내용]",
          "title": "[U_20_3] (systemd.conf 권한 설정)",
          "cmd": "chmod 600 /etc/systemd.conf, chown root /etc/systemd.conf",
          "result": "조치 성공 (systemd.conf 및 하위 폴더 권한 설정)"
         } | to_json
        }}
      when: "'U_20_3' in flag_list" 

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_20_3",
          "section": "[조치 내용]",
          "title": "[U_20_3] (systemd.conf 하위 폴더 권한 설정)",
          "cmd": "chmod 600 /etc/systemd.d/, chown -R root /etc/systemd.d/",
          "result": "조치 성공 (systemd.conf 및 하위 폴더 권한 설정)"
         } | to_json
        }}
      when: "'U_20_3' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
      path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_20_3",
              "status": 2, 
              "description": "systemd.conf 및 하위 파일 권한 설정 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_20_3' in flag_list" 