---
- name: "U-53 FTP 서비스 정보 노출 제한 설정"
  hosts: all
  become: yes
  vars:
   file: "system"
   flag_list: []
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/ubuntu24-remediate_{{ flag_list }}.log"
   my_json_file: "{{ json_dir }}/ubuntu24-remediate_{{ flag_list }}.json"
  tasks: 
    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_53_1",
          "section": "[조치 내용]",
          "title": "[U_53_1] ()",
          "cmd": " ",
          "result": "조치 성공 ()"
         } | to_json
        }}
      when: "'U_53_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_53_1",
              "status": 2, 
              "description": " ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_53_1' in flag_list"
    
    # 1. FTP 서비스 실행 상태 확인
    - name: "1. FTP 서비스(vsftpd, proftpd) 상태 확인"
      ansible.builtin.service_facts:
      register: services_state

    # 2. [vsFTP] 배너 설정 및 서비스 재시작
    - name: "2. [vsFTP] 배너 정보 노출 제한 설정"
      block:
        - name: "2-1. vsftpd.conf 내 ftpd_banner 설정 수정 (Step 2)"
          ansible.builtin.lineinfile:
            path: "{{ item }}"
            regexp: '^\s*#?\s*ftpd_banner\s*='
            line: "ftpd_banner={{ custom_ftp_banner }}"
            state: present
          loop:
            - /etc/vsftpd.conf
            - /etc/vsftpd/vsftpd.conf
          register: vsftpd_update
          ignore_errors: yes

        - name: "2-2. vsFTP 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: vsftpd
            state: restarted
          when: vsftpd_update.changed
      when: 
      - "'vsftpd.service' in services_state.ansible_facts.services"
      - "'U_53_1' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_53_1",
          "section": "[조치 내용]",
          "title": "[U_53_1] ([vsFTP] 배너 정보 노출 제한 설정)",
          "cmd": " ftpd_banner=<변경할 배너> ",
          "result": "조치 성공 ([vsFTP] 배너 정보 노출 제한 설정)"
         } | to_json
        }}
      when: "'U_53_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_53_1",
              "status": 2, 
              "description": "[vsFTP] 배너 정보 노출 제한 설정 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_53_1' in flag_list"
    


    # 3. [ProFTP] 배너 설정 및 서비스 재시작 (Step 1~3)
    - name: "3. [ProFTP] ServerIdent 설정 수정"
      block:
        - name: "3-1. proftpd.conf 내 ServerIdent 설정 수정 (Step 2)"
          # 가이드 권장: ServerIdent off 또는 메시지 직접 지정
          ansible.builtin.lineinfile:
            path: "{{ item }}"
            regexp: '^\s*#?\s*ServerIdent\s+'
            line: 'ServerIdent off'
            state: present
          loop:
            - /etc/proftpd.conf
            - /etc/proftpd/proftpd.conf
          register: proftpd_update
          ignore_errors: yes

        - name: "3-2. ProFTP 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: proftpd
            state: restarted
          when: proftpd_update.changed
      when: 
      - "'proftpd.service' in services_state.ansible_facts.services"
      - "'U_53_2' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_53_2",
          "section": "[조치 내용]",
          "title": "[U_53_2] ([ProFTP] ServerIdent 설정 수정)",
          "cmd": " ServerIdent on “<변경할 배너>” ",
          "result": "조치 성공 ([ProFTP] ServerIdent 설정 수정)"
         } | to_json
        }}
      when: "'U_53_2' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_53_2",
              "status": 2, 
              "description": "[ProFTP] ServerIdent 설정 수정 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_53_2' in flag_list"
    
  