---
- name: 주요정보통신기반시설 보안 조치 - U-00 (  )
  hosts: all
  become: yes

  vars:
  # 예시를 위해 DB에서 받은 데이터를 가정 (실제로는 postgres_query 등으로 받음)
  # db_result.query_result[0].val 값이 '123'(숫자형 문자열)인지 'abc'(문자열)인지에 따라 분기
  # 1. 추출하고 싶은 Task 이름 리스트
    target_tasks: "{{ lookup('file', this_file) | regex_findall('name:\\s+\"(.*)\"', multiline=True) }}"
    this_file: "./U_00_fix.yaml"
    TS: "{{ ansible_date_time.iso8601 }}"
    FLAG_ID: "U-00"
    LOG_SECTION_STEP: "Step 1"
  tasks: 

   - name: "반복문을 이용한 블록 추출 및 변수 저장"
     vars:
        content_lines: "{{ lookup('file', this_file).splitlines() }}"
        # 각 item(Task 이름)에 대한 시작 인덱스 계산
        start_idx: >-
          {% for line in content_lines if 'name: "' ~ item ~ '"' in line %}{{ loop.index0 }}{% break %}{% endfor %}
        # 다음 Task 시작점까지의 길이 계산
        remaining: "{{ content_lines[start_idx|int + 1:] }}"
        end_offset: >-
          {% set offset = remaining | length %}
          {% for line in remaining %}
            {% if '  - name:' in line %}{{ loop.index0 }}{% break %}
            {% elif loop.last %}{{ offset }}{% endif %}
          {% endfor %}
     ansible.builtin.set_fact:
        # dict를 생성하여 { "Task이름": "추출내용" } 형태로 누적 저장
        extracted_results: "{{ extracted_results | default({}) | combine({ item: (content_lines[start_idx|int : start_idx|int + end_offset|int + 1] | join('\n')) }) }}"
     loop: "{{ target_tasks }}"
   
   - name: "추출된 Task 블록 결과 출력"
     ansible.builtin.debug:
        msg: >-
          {{
            {
              "ts": TS,
              "flag_id": FLAG_ID,
              "section": LOG_SECTION_STEP,
              "title": "[U-00] 보안 조치 실행 내용",
              "cmd": extracted_results[item] | default('내용을 찾을 수 없음'),
              "result": "task_name=" ~ item
            } | to_json
          }}
     loop: "{{ target_tasks }}"  # 각 추출된 결과별로 로그를 남기기 위해 루프 사용

   - name: "SYSRUN"
     ansible.builtin.debug:
      msg: >-
       {{
        {
         "ts": "2026-02-11T16:45:12Z",
         "flag_id": "U_34_*",
         "section": "[조치 내용]",
         "title": "[U_34_*] Finger 서비스 비활성화 및 프로세스 종료",
         "cmd": "쉘 코드"
         "result": "조치 성공 (설정 비활성화 및 프로세스 종료 완료)"
        }
       }}

   - name: "SYSOUT"
     ansible.builtin.debug:
        msg: >-
          {{
            {
              "ts": (r_ts1.stdout | default("")),
              "flag_id": FLAG_ID,
              "section": LOG_SECTION_STEP,
              "title": "[U_54_1] inetd.conf 내 ftp 라인 주석 처리",
              "cmd": "replace: regexp=^(?!#)(\\s*ftp\\s.*)$ -> '# \\1' @ " ~ inetd_conf,
              "result": "changed=" ~ (r_inetd_comment.changed | default(false) | bool) | string
                        ~ ", backup_file=" ~ (r_inetd_comment.backup_file | default("<none>"))
            } | to_json
          }}
     changed_when: false
#   - name : task2
#     
#
#   - name : LOG
#     loop: {{ }}
#     shell: ""
#     ansible.builtin.debug: 
#      msg: {{CL.run_cmd "U-14 PATH 환경변수 설정" "code 직접 \n 달기" }}
     

    