---
- name: 주요정보통신기반시설 보안 조치 - U-14 (PATH 환경변수 설정)
  hosts: all
  become: yes
  vars:
    target_files:
      - /etc/profile
      - /etc/bash.bashrc
      - /root/.profile
      - /root/.bashrc
      - /root/.bash_profile

  tasks:
    # 1. 파일들의 존재 여부를 먼저 확인합니다.
    - name: "PATH 설정 파일 존재 여부 확인"
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ target_files }}"
      register: file_stats

    # 2. 파일이 존재하는 경우(exists)에만 수정을 시도합니다.
    - name: "U-14: PATH 환경변수 내 '.' 포함 여부 확인 및 수정"
      ansible.builtin.replace:
        path: "{{ item.item }}"
        # PATH= 뒤에 오는 점(.) 또는 중간의 :.: 패턴을 찾아 변경
        regexp: '(?<=PATH=)(\.:|:.:)'
        replace: ':'
      loop: "{{ file_stats.results }}"
      # stat 결과에서 exists가 true인 경우에만 실행
      when: item.stat.exists
      register: patch_result