---
- name: 주요정보통신기반시설 보안 조치 - U-17 ( 시스템 시작 스크립트 파일 권한 적절성 여부 점검 )
  hosts: all
  become: yes

  vars:
  # 예시를 위해 DB에서 받은 데이터를 가정 (실제로는 postgres_query 등으로 받음)
  # db_result.query_result[0].val 값이 '123'(숫자형 문자열)인지 'abc'(문자열)인지에 따라 분기
   target_files:
     - /etc/rc.d
     - /etc/systemd/system
   target_owner: "root"
   target_group: "root"
   target_tasks: "{{ lookup('file', this_file) | regex_findall('name:\\s+\"(.*)\"', multiline=True) }}"
   this_file: "./U_17_fix.yaml"
  tasks:
   - name: " 시스템 시작 스크립트 파일 소유자 및 권한 변경"
      # 이미지의 '조치 방법'에 따라 소유자 및 그룹을 변경함
      # (실제 환경에 따라 제거(rm)가 필요할 경우 file 모듈의 state: absent 사용)
     ansible.builtin.file:
      path: "{{ item }}"
      owner: "{{ target_owner }}"
      group: "{{ target_group }}"
      mode: '644'
     loop: "{{ target_files }}"
   