---
- name: 주요정보통신기반시설 보안 조치 - U-21 ( /etc/(r)syslog.conf 파일 권한 적절성 여부 점검 )
  hosts: all
  become: yes

  vars:
    # 리스트 형식(-)으로 정확히 정의해야 합니다.
    target_files:
      - /etc/syslog.conf
      - /etc/rsyslog.conf

  tasks: 
   - name: "/etc/(r)syslog.conf 파일 상태 확인"
     ansible.builtin.stat:
       path: "{{ item }}"
     loop: "{{ target_files }}"
     register: syslog_stats

   - name: "파일이 존재할 때만 권한 변경"
     ansible.builtin.file:
       path: "{{ item.item }}"
       owner: root
       group: root
       mode: '0640'
     loop: "{{ syslog_stats.results }}"
     # 파일이 실제로 존재할 때만 실행하여 에러 방지
     when: item.stat.exists