---
- name: 주요정보통신기반시설 보안 조치 - U-23 ( SUID, SGID, Sticky bit 설정 파일 점검 )
  hosts: all
  become: yes

#########################  수 동 권 장 #####################

  vars:
  # 예시를 위해 DB에서 받은 데이터를 가정 (실제로는 postgres_query 등으로 받음)
  # db_result.query_result[0].val 값이 '123'(숫자형 문자열)인지 'abc'(문자열)인지에 따라 분기
  
  tasks: 
   - name: "1. SUID/SGID 설정된 파일 검색 (가이드 Step 1 기준)"
      # 가이드의 find 명령어를 사용하여 루트 권한의 SUID(4000), SGID(2000) 파일을 찾습니다.
     ansible.builtin.shell: |
        find / -user root -type f \( -perm -04000 -o -perm -02000 \) -xdev -exec ls -al {} \; 2>/dev/null
     register: special_perm_files
     changed_when: false
   - name: "2. 검색된 파일 목록 출력"
     ansible.builtin.debug:
        msg: |
          [점검 결과] 아래 파일들에 SUID/SGID가 설정되어 있습니다. 
          불필요한 파일이 있는지 확인하십시오.
          {{ special_perm_files.stdout_lines }}

   - name: "3. [조치 예시] 불필요한 SUID/SGID 제거 (필요 시 주석 해제)"
      # 가이드 Step 2: chmod -s <파일 이름>
      # 실제 운영 환경에서는 서비스 영향도를 고려하여 제거 대상을 명확히 정해야 합니다.
     ansible.builtin.file:
        path: "{{ item }}"
        mode: "-s"
     loop:
        - /usr/bin/bad_file  # 예시: 제거가 필요한 파일 경로 입력
     when: false  # 안전을 위해 기본적으로 실행되지 않도록 설정

   - name: "4. [조치 예시] 특정 그룹으로 사용 제한 (필요 시 주석 해제)"
      # 가이드 Step 3: 특정 그룹만 사용 가능하도록 제한
     ansible.builtin.file:
        path: /usr/bin/restricted_file
        group: trusted_group
        mode: '4750'
     when: false