---
- name: "U-24 사용자 및 시스템 환경변수 파일 권한 설정 점검"
  hosts: all
  become: yes
  vars:
    env_files:
      - ".profile"
      - ".kshrc"
      - ".cshrc"
      - ".bashrc"
      - ".bash_profile"
      - ".login"
      - ".exrc"
      - ".netrc"

  tasks:
    - name: "1. 시스템 내 일반 사용자 목록 추출"
      ansible.builtin.shell: "awk -F: '$3 >= 1000 {print $1\":\"$6}' /etc/passwd"
      register: user_list
      changed_when: false

    - name: "2. 사용자 데이터 정제"
      set_fact:
        refined_users: "{{ refined_users | default([]) + [{'user': item.split(':')[0], 'home': item.split(':')[1]}] }}"
      loop: "{{ user_list.stdout_lines }}"

    - name: "3. 모든 환경변수 파일의 존재 여부 확인"
      ansible.builtin.stat:
        path: "{{ item.1.home }}/{{ item.0 }}"
      register: env_file_stats
      with_nested:
        - "{{ env_files }}"
        - "{{ refined_users }}"
      loop_control:
        label: "Checking {{ item.1.user }}'s {{ item.0 }}"

    - name: "4. 파일이 존재하는 경우에만 소유자 및 권한 조치"
      ansible.builtin.file:
        path: "{{ item.item.1.home }}/{{ item.item.0 }}"
        owner: "{{ item.item.1.user }}"
        mode: 'o-w'
      loop: "{{ env_file_stats.results }}"
      loop_control:
        label: "Remediating {{ item.item.1.user }}'s {{ item.item.0 }}"
      # 핵심 수정 부분: stat 결과에서 파일이 존재(exists)할 때만 실행
      when: item.stat.exists

    - name: "5. 결과 요약 출력"
      ansible.builtin.debug:
        msg: "존재하는 모든 사용자의 환경변수 파일에 대해 조치를 완료했습니다."