---
- name: "U-25 World Writable 파일 점검 및 조치"
  hosts: all
  become: yes
  tasks:
    - name: "1. 시스템 내 World Writable 파일 검색 (가이드 Step 1)"
      # 가이드의 find 명령어를 사용하여 일반 사용자 쓰기 권한(-perm -2)이 있는 파일 탐색
      # 시스템 부하 방지를 위해 -xdev 옵션 추가 및 에러 메시지 제외
      ansible.builtin.shell: |
        find / -type f -perm -2 -xdev -ls 2>/dev/null
      register: world_writable_files
      changed_when: false

    - name: "2. 검색 결과 출력"
      ansible.builtin.debug:
        msg: |
          [점검 결과] 아래 파일들에 World Writable 권한이 설정되어 있습니다.
          {{ world_writable_files.stdout_lines }}

    - name: "3. [조치] 일반 사용자 쓰기 권한 제거 (가이드 Step 2)"
      # 가이드 조치 사례: chmod o-w <파일 이름>
      # 검색된 파일이 있을 경우에만 실행됩니다.
      ansible.builtin.file:
        path: "{{ item.split()[-1] }}" # ls -ls 결과에서 파일 경로만 추출
        mode: "o-w"
      loop: "{{ world_writable_files.stdout_lines }}"
      when: world_writable_files.stdout_lines | length > 0
      register: remediation_output

    - name: "4. 조치 완료 확인"
      ansible.builtin.debug:
        msg: "불필요한 World Writable 권한 제거를 완료했습니다."
      when: remediation_output.changed