---
- name: "U-26 /dev에 존재하지 않는 device 파일 점검 및 조치"
  hosts: all
  become: yes
  tasks:
    - name: "1. /dev 내 일반 파일(정상 디바이스가 아닌 파일) 검색"
      # 가이드 Step 1: find /dev -type f를 통해 장치 파일이 아닌 일반 파일을 찾습니다.
      # 시스템 생성 파일인 mqueue, shm은 제외합니다.
      ansible.builtin.shell: |
        find /dev -type f ! -name "mqueue" ! -name "shm" -exec ls -l {} \; 2>/dev/null
      register: invalid_dev_files
      changed_when: false

    - name: "2. 점검 결과 출력"
      ansible.builtin.debug:
        msg: |
          [점검 결과] /dev 디렉터리 내에 비정상적인 일반 파일이 존재합니다:
          {{ invalid_dev_files.stdout_lines }}
      when: invalid_dev_files.stdout_lines | length > 0

    - name: "3. [조치] 비정상 파일 삭제 (가이드 Step 1)"
      # 가이드 조치 사례: # rm <파일 이름>
      # major, minor 번호를 가지지 않는 일반 파일(type f)을 삭제합니다.
      ansible.builtin.file:
        path: "{{ item.split()[-1] }}"
        state: absent
      loop: "{{ invalid_dev_files.stdout_lines }}"
      when: invalid_dev_files.stdout_lines | length > 0
      register: rm_result

    - name: "4. 최종 상태 보고"
      ansible.builtin.debug:
        msg: >-
          {% if invalid_dev_files.stdout_lines | length == 0 %}
          양호: /dev 내에 불필요한 파일이 존재하지 않습니다.
          {% else %}
          조치완료: {{ rm_result.results | length }}개의 비정상 파일을 제거했습니다.
          {% endif %}