---
- name: "U-27 $HOME/.rhosts, hosts.equiv 사용 금지 및 설정 점검"
  hosts: all
  become: yes
  tasks:
    - name: "1. 시스템 내 모든 사용자의 홈 디렉터리 및 계정 정보 수집"
      ansible.builtin.getent:
        database: passwd

    - name: "2. 점검 대상 파일 목록 생성 (/etc/hosts.equiv 및 모든 사용자의 .rhosts)"
      ansible.builtin.set_fact:
        rhost_files: >-
          {{
            ['/etc/hosts.equiv'] +
            (getent_passwd.values() | map(attribute=4) | map('regex_replace', '$', '/.rhosts') | list)
          }}

    - name: "3. 대상 파일 정보 확인 (존재 여부, 소유자, 권한)"
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ rhost_files }}"
      register: rhost_stats

    - name: "4. [조치] 소유자 변경, 권한 설정 및 '+' 설정 제거"
      block:
        - name: "4-1. 소유자 root(또는 해당 계정) 및 권한 600 설정"
          ansible.builtin.file:
            path: "{{ item.item }}"
            owner: "root"  # 기본적으로 root로 설정하거나 필요시 해당 사용자로 변경
            mode: '0600'
          loop: "{{ rhost_stats.results }}"
          when: item.stat.exists

        - name: "4-2. 파일 내 '+' 설정(모든 호스트/계정 신뢰) 제거"
          ansible.builtin.replace:
            path: "{{ item.item }}"
            regexp: '^\s*\+\s*.*$'
            replace: ''
          loop: "{{ rhost_stats.results }}"
          when: item.stat.exists
      
    - name: "5. 최종 결과 리포트"
      ansible.builtin.debug:
        msg: "모든 .rhosts 및 hosts.equiv 파일에 대한 권한 강화 및 취약 설정(+) 제거를 완료했습니다."