---
- name: 주요정보통신기반시설 보안 조치 - U-29 ( hosts.lpd 파일 소유자 및 권한 설정 )
  hosts: all
  become: yes

  vars:
  # 예시를 위해 DB에서 받은 데이터를 가정 (실제로는 postgres_query 등으로 받음)
  # db_result.query_result[0].val 값이 '123'(숫자형 문자열)인지 'abc'(문자열)인지에 따라 분기
  
  tasks: 
   - name: "/etc/hosts.lpd 파일 존재 여부 확인"
     ansible.builtin.stat:
       path: /etc/hosts.lpd
     register: lpd_stat

   - name: "4. [조치] 파일이 존재할 경우 소유자 및 권한 변경"
     ansible.builtin.file:
        path: /etc/hosts.lpd
        owner: root
        group: root
        mode: '0600'
        state: file  # 파일이 있을 때만 속성을 변경함
     when: lpd_stat.stat.exists  # 파일이 존재할 때만 이 태스크를 실행함