---
- name: "U-31 홈디렉토리 소유자 및 권한 설정 점검"
  hosts: all
  become: yes
  tasks:
    - name: "1. 시스템 내 일반 사용자 및 홈 디렉토리 정보 수집"
      # 블록 스타일(|)을 사용하여 특수문자 충돌을 방지합니다.
      ansible.builtin.shell: |
        awk -F: '$3 >= 1000 && $6 !~ /^\/nonexistent/ {print $1":"$6}' /etc/passwd
      register: user_home_list
      changed_when: false

    - name: "2. 각 사용자별 홈 디렉토리 소유자 및 권한 점검/조치"
      ansible.builtin.file:
        path: "{{ item.split(':')[1] }}"
        owner: "{{ item.split(':')[0] }}"
        mode: "o-w"
        state: directory
      loop: "{{ user_home_list.stdout_lines }}"
      # 리스트 인덱스 접근 시 .1 대신 [1] 형식을 권장합니다.
      when: 
        - item.split(':') | length >= 2
        - item.split(':')[1] != ''
        - item.split(':')[1] != '/'
      ignore_errors: yes

    - name: "3. 결과 요약 출력"
      ansible.builtin.debug:
        msg: "일반 사용자 홈 디렉토리 보안 조치를 완료했습니다."