---
- name: "U-33 숨겨진 파일 및 디렉토리 검색 및 점검"
  hosts: all
  become: yes
  tasks:
    - name: "1. 숨겨진 파일 검색 (Step 2: find -type f -name '.*')"
      # 이미지 가이드의 find 명령어를 사용하여 루트(/)부터 숨겨진 파일을 찾습니다.
      # 시스템 부하 방지를 위해 -xdev 옵션과 주요 시스템 디렉토리 제외를 권장합니다.
      ansible.builtin.shell: |
        find / -type f -name ".*" -xdev -ls 2>/dev/null | grep -vE '/(proc|sys|run|dev|var/lib/docker)/'
      register: hidden_files
      changed_when: false

    - name: "2. 숨겨진 디렉토리 검색 (Step 2: find -type d -name '.*')"
      # 이미지 가이드의 find 명령어를 사용하여 숨겨진 디렉토리를 찾습니다.
      ansible.builtin.shell: |
        find / -type d -name ".*" -xdev -ls 2>/dev/null | grep -vE '/(proc|sys|run|dev|var/lib/docker)/'
      register: hidden_dirs
      changed_when: false

    - name: "3. 검색된 숨겨진 파일 및 디렉토리 목록 출력"
      ansible.builtin.debug:
        msg: |
          [점검 결과] 아래의 숨겨진 항목들이 발견되었습니다. 의심스러운 항목이 있는지 검토하십시오.
          
          ### 숨겨진 파일 목록 ###
          {{ hidden_files.stdout_lines }}
          
          ### 숨겨진 디렉토리 목록 ###
          {{ hidden_dirs.stdout_lines }}

    - name: "4. [조치 예시] 불필요하거나 의심스러운 항목 제거 (Step 3)"
      # 가이드 조치 사례: # rm <파일 이름>, # rm -r <디렉토리 이름>
      # 실제 운영 환경에서는 필수 설정 파일(.bashrc 등)이 삭제되지 않도록 주의가 필요하여 예시로만 작성합니다.
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/.hidden_malicious_file" # 예시: 삭제가 필요한 의심 파일 경로
      when: false  # 안전을 위해 기본적으로 실행되지 않도록 설정