---
- name: "U-45 메일 서비스 버전 점검 및 비활성화 (이미지 가이드 반영)"
  hosts: all
  become: yes
  tasks:
    # 1. 서비스 상태 확인 (가이드 공통 Step 1: 활성화 여부 확인)
    - name: "1. 메일 서비스(Sendmail, Postfix, Exim) 상태 확인"
      ansible.builtin.service_facts:
      register: services_state

    # 2. [Sendmail] 조치
    - name: "2. [Sendmail] 조치"
      block:
        - name: "Sendmail 버전 확인 (사용하는 경우)"
          ansible.builtin.shell: "sendmail -d0.1 -bt < /dev/null | grep Version" # 가이드: sendmail -d0 -bt
          register: sendmail_ver
          when: "'sendmail.service' in services_state.ansible_facts.services and services_state.ansible_facts.services['sendmail.service'].state == 'running'"

        - name: "Sendmail 서비스 중지 및 비활성화 (사용하지 않는 경우)"
          ansible.builtin.systemd:
            name: sendmail
            state: stopped
            enabled: no
          when: "'sendmail.service' in services_state.ansible_facts.services and services_state.ansible_facts.services['sendmail.service'].state != 'running'"

    # 3. [Postfix] 조치
    - name: "3. [Postfix] 조치"
      block:
        - name: "Postfix 버전 확인 (사용하는 경우)"
          ansible.builtin.shell: "postconf mail_version" # 가이드: postconf mail_version
          register: postfix_ver
          when: "'postfix.service' in services_state.ansible_facts.services and services_state.ansible_facts.services['postfix.service'].state == 'running'"

        - name: "Postfix 서비스 종료 (사용하지 않는 경우)"
          # 가이드: ps -ef | grep postfix 후 kill -9 <PID>
          ansible.builtin.shell: "pkill -9 postfix"
          when: "'postfix.service' in services_state.ansible_facts.services and services_state.ansible_facts.services['postfix.service'].state != 'running'"
          ignore_errors: yes

    # 4. [Exim] 조치
    - name: "4. [Exim] 조치"
      block:
        - name: "Exim 서비스 활성화 여부 확인 및 패치 안내 (사용하는 경우)"
          ansible.builtin.debug:
            msg: "Exim 서비스가 활성화되어 있습니다. 최신 버전 확인 및 보안 패치를 진행하십시오. (https://www.exim.org/)"
          when: "('exim.service' in services_state.ansible_facts.services or 'exim4.service' in services_state.ansible_facts.services)"

        - name: "Exim 서비스 종료 (사용하지 않는 경우)"
          # 가이드: ps -ef | grep exim 후 서비스 종료
          ansible.builtin.shell: "pkill -9 exim"
          when: "('exim.service' in services_state.ansible_facts.services or 'exim4.service' in services_state.ansible_facts.services)"
          ignore_errors: yes

    # 5. 공통 패치 권고 (최신 버전 확인 및 보안 패치 진행)
    - name: "5. 보안 패치 적용 (가이드 Step 2 공통)"
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      loop: ["sendmail", "postfix", "exim"]
      when: "item + '.service' in services_state.ansible_facts.services"