---
- name: "U-46 일반 사용자의 메일 서비스 실행 방지"
  hosts: all
  become: yes
  tasks:
    # 1. 공통: 메일 서비스를 사용하지 않는 경우 서비스 중지 (조치 방법 기준)
    - name: "1. 메일 서비스 활성화 여부 확인"
      ansible.builtin.service_facts:
      register: services_state

    # 2. [Sendmail] 조치 (Step 1, 2)
    - name: "2. [Sendmail] PrivacyOptions 설정 강화"
      block:
        - name: "Sendmail 설정 파일 내 restrictqrun 옵션 추가"
          ansible.builtin.replace:
            path: /etc/mail/sendmail.cf
            regexp: '^O\s+PrivacyOptions=(.*)'
            replace: 'O PrivacyOptions=\1,restrictqrun'
          register: sendmail_conf_update
          # 이미 설정되어 있는지 확인하여 중복 추가 방지
          when: "('sendmail.service' in services_state.ansible_facts.services) and ('restrictqrun' not in lookup('file', '/etc/mail/sendmail.cf'))"

        - name: "Sendmail 서비스 재시작"
          ansible.builtin.systemd:
            name: sendmail
            state: restarted
          when: sendmail_conf_update.changed

    # 3. [Postfix] 조치 (Step 1, 2)
    - name: "3. [Postfix] postsuper 실행 권한 제거"
      ansible.builtin.file:
        path: /usr/sbin/postsuper
        mode: 'o-x' # 일반 사용자(others)의 실행(x) 권한 제거
      when: "'postfix.service' in services_state.ansible_facts.services"

    # 4. [Exim] 조치 (Step 1, 2)
    - name: "4. [Exim] exiqgrep 실행 권한 제거"
      ansible.builtin.file:
        path: /usr/sbin/exiqgrep
        mode: 'o-x' # 일반 사용자(others)의 실행(x) 권한 제거
      when: "'exim.service' in services_state.ansible_facts.services or 'exim4.service' in services_state.ansible_facts.services"