---
- name: "U-47 스팸 메일 릴레이 제한 설정 (Sendmail)"
  hosts: all
  become: yes
  vars:
    # 허용할 네트워크 주소 (운영 환경에 맞게 수정 필요)
    allow_networks: "127.0.0.0/8 [::1]/128"

  tasks:
    # 1. 메일 서비스 활성화 여부 확인 (점검 대상 확인)
    - name: "1. 서비스 상태 확인"
      ansible.builtin.service_facts:
      register: services_state

    # 2. 메일 서비스를 사용하지 않는 경우 (조치 방법 기준)
    - name: "2. [조치] 메일 서비스 미사용 시 서비스 중지 및 비활성화"
      ansible.builtin.systemd:
        name: sendmail
        state: stopped
        enabled: no
      when: 
        - "'sendmail.service' in services_state.ansible_facts.services"
        - "services_state.ansible_facts.services['sendmail.service'].state != 'running'"

    # 3. 메일 서비스 사용 시 릴레이 제한 설정 (Step 2, 3, 4)
    - name: "3. [조치] Sendmail 릴레이 제한 설정"
      block:
        - name: "3-1. promiscuous_relay 설정 제거 (Step 2)"
          ansible.builtin.lineinfile:
            path: /etc/mail/sendmail.mc
            regexp: "^FEATURE\\('promiscuous_relay'\\)dnl"
            state: absent
          register: mc_update

        - name: "3-2. sendmail.cf 설정 파일 재생성 (Step 3)"
          ansible.builtin.shell: "m4 /etc/mail/sendmail.mc > /etc/mail/sendmail.cf"
          when: mc_update.changed

        - name: "3-3. /etc/mail/access 파일에 신뢰할 수 있는 대상만 RELAY 설정 (Step 4)"
          ansible.builtin.blockinfile:
            path: /etc/mail/access
            block: |
              localhost.localdomain           RELAY
              localhost                       RELAY
              127.0.0.1                       RELAY
              # 스팸 도메인 차단 예시
              spam.com                        REJECT
            create: yes
          register: access_update

        - name: "3-4. access.db 데이터베이스 파일 생성 (Step 4)"
          ansible.builtin.shell: "makemap hash /etc/mail/access.db < /etc/mail/access"
          when: access_update.changed

        - name: "3-5. 설정 적용 및 Sendmail 재시작 (Step 5)"
          ansible.builtin.systemd:
            name: sendmail
            state: restarted
          when: mc_update.changed or access_update.changed

      when: 
        - "'sendmail.service' in services_state.ansible_facts.services"
        - "services_state.ansible_facts.services['sendmail.service'].state == 'running'"

        # --- [Sendmail 8.9 미만 버전 조치] ---
    - name: "2. [Sendmail] 릴레이 제한 설정 (Step 2, 3, 4)"
      block:
        - name: "Sendmail 릴레이 거부 메시지 설정 (Step 2)"
          ansible.builtin.lineinfile:
            path: /etc/mail/sendmail.cf
            regexp: '^RS\*'
            line: 'RS* $#error $@ 5.7.1 $: "550 Relaying denied"'

        - name: "접근 제한 파일(access) 설정 (Step 3)"
          ansible.builtin.blockinfile:
            path: /etc/mail/access
            block: |
              localhost.localdomain           RELAY
              localhost                       RELAY
              127.0.0.1                       RELAY
            create: yes
          register: access_db_update

        - name: "access.db 파일 생성 (Step 4)"
          ansible.builtin.shell: "makemap hash /etc/mail/access.db < /etc/mail/access"
          when: access_db_update.changed
      when: "'sendmail.service' in services_state.ansible_facts.services"

    # --- [Postfix 조치] ---
    - name: "3. [Postfix] 릴레이 정책 설정 (Step 2, 3)"
      block:
        - name: "허용할 네트워크 주소 설정 (Step 2)"
          ansible.builtin.lineinfile:
            path: /etc/postfix/main.cf
            regexp: '^mynetworks\s*='
            line: "mynetworks = {{ allow_networks }}"
          register: postfix_update

        - name: "Postfix 설정 적용 (Step 3)"
          ansible.builtin.shell: "postfix reload"
          when: postfix_update.changed
      when: "'postfix.service' in services_state.ansible_facts.services"

    # --- [Exim 조치] ---
    - name: "4. [Exim] 릴레이 허용 네트워크 설정 (Step 2, 3)"
      block:
        - name: "Exim 설정 파일 경로 확인"
          ansible.builtin.set_fact:
            exim_conf: "{{ '/etc/exim4/exim4.conf' if query('file', '/etc/exim4/exim4.conf') else '/etc/exim/exim.conf' }}"

        - name: "릴레이 허용 호스트 리스트 수정 (Step 2)"
          ansible.builtin.lineinfile:
            path: "{{ exim_conf }}"
            regexp: '^hostlist relay_from_hosts\s*='
            line: "hostlist relay_from_hosts = {{ allow_networks }}"
          register: exim_update

        - name: "Exim 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: "{{ 'exim4' if 'exim4.service' in services_state.ansible_facts.services else 'exim' }}"
            state: restarted
          when: exim_update.changed
      when: "'exim.service' in services_state.ansible_facts.services or 'exim4.service' in services_state.ansible_facts.services"