---
- name: "U-51 DNS 서비스의 취약한 동적 업데이트 설정 금지 (BIND)"
  hosts: all
  become: yes
  vars:
    # 동적 업데이트가 필요한 경우 허용할 IP (필요 시 수정, 불필요 시 none)
    allowed_update_ips: "none" 

  tasks:
    # 1. DNS 서비스 활성화 여부 확인 (Step 1)
    - name: "1. BIND 서비스(named) 상태 확인"
      ansible.builtin.service_facts:
      register: services_state

    # 2. DNS 서비스를 사용하지 않는 경우 (조치 방법 기준)
    - name: "2. [조치] DNS 미사용 시 서비스 중지 및 비활성화"
      ansible.builtin.systemd:
        name: named
        state: stopped
        enabled: no
      when: 
        - "'named.service' in services_state.ansible_facts.services"
        - "services_state.ansible_facts.services['named.service'].state != 'running'"

    # 3. DNS 서비스 사용 시 동적 업데이트 제한 설정 (Step 1~3)
    - name: "3. [조치] allow-update 설정 적용"
      block:
        - name: "3-1. 설정 파일 내 allow-update 값 수정 (Step 2)"
          # 이미지 가이드의 allow-update { none; }; 또는 특정 IP 설정을 적용합니다.
          ansible.builtin.replace:
            path: "{{ item }}"
            regexp: 'allow-update\s*\{[^}]*\};'
            replace: "allow-update { {{ allowed_update_ips }}; };"
          loop:
            - /etc/named.conf
            - /etc/bind/named.conf.options
          register: update_config
          ignore_errors: yes

        - name: "3-2. 설정이 없을 경우 기본값(none)으로 추가"
          ansible.builtin.lineinfile:
            path: "{{ item }}"
            line: "        allow-update { {{ allowed_update_ips }}; };"
            insertafter: 'options \{'
            state: present
          loop:
            - /etc/named.conf
            - /etc/bind/named.conf.options
          when: not update_config.changed
          ignore_errors: yes
          register: line_add_config

        - name: "3-3. DNS 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: named
            state: restarted
          when: update_config.changed or line_add_config.changed

      when: 
        - "'named.service' in services_state.ansible_facts.services"
        - "services_state.ansible_facts.services['named.service'].state == 'running'"

    # 4. 결과 출력
    - name: "4. 최종 점검 결과 요약"
      ansible.builtin.debug:
        msg: "DNS 동적 업데이트 기능을 '{{ allowed_update_ips }}'(으)로 제한 설정 완료하였습니다."