---
- name: "U-52 Telnet 서비스 비활성화 및 SSH 사용 설정"
  hosts: all
  become: yes
  tasks:
    # 0. 서비스 상태 수집 (서비스 존재 여부 확인용)
    - name: "0. 시스템 서비스 정보 수집"
      ansible.builtin.service_facts:
      register: services_state

    # 1. [inetd] 환경 조치
    - name: "1. [inetd] 파일 확인 및 조치"
      block:
        - name: "1-1. /etc/inetd.conf 존재 확인"
          ansible.builtin.stat:
            path: /etc/inetd.conf
          register: inetd_file

        - name: "1-2. /etc/inetd.conf 내 Telnet 주석 처리"
          ansible.builtin.replace:
            path: /etc/inetd.conf
            regexp: '^(\s*telnet\s+.*)$'
            replace: '# \1'
          when: inetd_file.stat.exists
          register: inetd_update

        - name: "1-3. inetd 서비스 재시작"
          ansible.builtin.service:
            name: inetd
            state: restarted
          when: 
            - inetd_file.stat.exists 
            - inetd_update.changed 
            - "'inetd.service' in services_state.ansible_facts.services"
      ignore_errors: yes

    # 2. [xinetd] 환경 조치
    - name: "2. [xinetd] 파일 확인 및 조치"
      block:
        - name: "2-1. /etc/xinetd.d/telnet 존재 확인"
          ansible.builtin.stat:
            path: /etc/xinetd.d/telnet
          register: xinetd_file

        - name: "2-2. /etc/xinetd.d/telnet 파일 수정"
          ansible.builtin.lineinfile:
            path: /etc/xinetd.d/telnet
            regexp: '^\s*disable\s*='
            line: "\tdisable = yes"
          when: xinetd_file.stat.exists
          register: xinetd_update

        - name: "2-3. xinetd 서비스 재시작"
          ansible.builtin.systemd:
            name: xinetd
            state: restarted
          when: 
            - xinetd_file.stat.exists 
            - xinetd_update.changed
            - "'xinetd.service' in services_state.ansible_facts.services"
      ignore_errors: yes

    # 3. [systemd] 환경 조치
    - name: "3. [systemd] Telnet 소켓 및 서비스 중지/비활성화"
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        masked: yes
      loop:
        - telnet.socket
        - telnet.service
      # 서비스가 시스템에 존재할 때만 실행
      when: "item in services_state.ansible_facts.services"
      ignore_errors: yes

    # 4. SSH 서비스 활성화
    - name: "4. SSH 서비스 실행 및 자동 시작 설정"
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: yes
      when: "'sshd.service' in services_state.ansible_facts.services"

    - name: "5. 최종 점검 결과 요약"
      ansible.builtin.debug:
        msg: "설정 파일 및 서비스 존재 여부를 확인하여 필요한 보안 조치를 완료했습니다."