---
- name: "U-53 FTP 서비스 정보 노출 제한 설정"
  hosts: all
  become: yes
  vars:
    # 변경할 배너 메시지 (이미지 권장사항: 서비스 이름/버전 제외)
    custom_ftp_banner: "Welcome to FTP Service"

  tasks:
    # 1. FTP 서비스 실행 상태 확인
    - name: "1. FTP 서비스(vsftpd, proftpd) 상태 확인"
      ansible.builtin.service_facts:
      register: services_state

    # 2. [vsFTP] 배너 설정 및 서비스 재시작 (Step 1~3)
    - name: "2. [vsFTP] 배너 정보 노출 제한 설정"
      block:
        - name: "2-1. vsftpd.conf 내 ftpd_banner 설정 수정 (Step 2)"
          ansible.builtin.lineinfile:
            path: "{{ item }}"
            regexp: '^\s*#?\s*ftpd_banner\s*='
            line: "ftpd_banner={{ custom_ftp_banner }}"
            state: present
          loop:
            - /etc/vsftpd.conf
            - /etc/vsftpd/vsftpd.conf
          register: vsftpd_update
          ignore_errors: yes

        - name: "2-2. vsFTP 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: vsftpd
            state: restarted
          when: vsftpd_update.changed
      when: "'vsftpd.service' in services_state.ansible_facts.services"

    # 3. [ProFTP] 배너 설정 및 서비스 재시작 (Step 1~3)
    - name: "3. [ProFTP] ServerIdent 설정 수정"
      block:
        - name: "3-1. proftpd.conf 내 ServerIdent 설정 수정 (Step 2)"
          # 가이드 권장: ServerIdent off 또는 메시지 직접 지정
          ansible.builtin.lineinfile:
            path: "{{ item }}"
            regexp: '^\s*#?\s*ServerIdent\s+'
            line: 'ServerIdent off'
            state: present
          loop:
            - /etc/proftpd.conf
            - /etc/proftpd/proftpd.conf
          register: proftpd_update
          ignore_errors: yes

        - name: "3-2. ProFTP 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: proftpd
            state: restarted
          when: proftpd_update.changed
      when: "'proftpd.service' in services_state.ansible_facts.services"

    # 4. 결과 리포트
    - name: "4. 최종 점검 결과 요약"
      ansible.builtin.debug:
        msg: "FTP 서비스 배너의 정보 노출 방지 설정을 완료했습니다."