- name: "[U_01] Remediate Root Remote Access Restriction"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    
    flag_id_main: "U_01"
    category: "account"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_01_1] Telnet root 접속 제한 (PAM & Securetty)
    # =========================================================
    - name: "[U_01_1] Block for Telnet Root Access Remediation"
      when: "'U_01_1' in flag_list"
      block:
        # -----------------------------------------------------
        # 실제 조치 태스크 시작
        # -----------------------------------------------------
        - name: "[U_01_1] Configure /etc/pam.d/login for pam_securetty"
          lineinfile:
            path: /etc/pam.d/login
            state: present
            insertafter: EOF
            line: 'auth required pam_securetty.so'
            regexp: '^auth\s+required\s+.*pam_securetty\.so'
          register: r_pam

        - name: "[U_01_1] Check if /etc/securetty exists"
          stat:
            path: /etc/securetty
          register: st_securetty

        - name: "[U_01_1] Comment out pts in /etc/securetty"
          replace:
            path: /etc/securetty
            regexp: '^(pts/.*)$'
            replace: '#\1'
          when: st_securetty.stat.exists
          register: r_securetty
        # -----------------------------------------------------
        # 실제 조치 태스크 끝
        # -----------------------------------------------------

        # [성공 로그: Status 2]
        - name: "Log U_01_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_01_1",
                  "status": 2,
                  "description": "Telnet Root 접속 제한(pam_securetty, securetty) 조치 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_01_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_01_1",
                "section": "[조치 결과]",
                "title": "[U_01_1] Telnet Root 접속 제한 설정 성공",
                "cmd": "pam_securetty.so 설정 및 securetty 수정 완료",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_01_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_01_1",
                  "status": 0,
                  "description": "조치 실패: Telnet Root 접속 제한 설정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_01_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_01_1",
                "section": "[조치 결과]",
                "title": "[U_01_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 상세 에러는 Ansible 로그 확인 필요"
              }

    # =========================================================
    # 2. [U_01_2] SSH root 접속 제한 (PermitRootLogin No)
    # =========================================================
    - name: "[U_01_2] Block for SSH Root Access Remediation"
      when: "'U_01_2' in flag_list"
      block:
        # -----------------------------------------------------
        # 실제 조치 태스크 시작
        # -----------------------------------------------------
        - name: "[U_01_2] Edit sshd_config to deny root login"
          lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^#?PermitRootLogin'
            line: 'PermitRootLogin no'
            state: present
            validate: /usr/sbin/sshd -t -f %s
          register: r_sshd_config

        - name: "[U_01_2] Restart SSH service"
          service:
            name: sshd
            state: restarted
          when: r_sshd_config.changed
        # -----------------------------------------------------
        # 실제 조치 태스크 끝
        # -----------------------------------------------------

        # [성공 로그: Status 2]
        - name: "Log U_01_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_01_2",
                  "status": 2,
                  "description": "SSH Root 접속 차단(PermitRootLogin no) 조치 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_01_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_01_2",
                "section": "[조치 결과]",
                "title": "[U_01_2] SSH Root 접속 제한 설정 성공",
                "cmd": "sshd_config 수정 및 서비스 재시작 완료",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_01_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_01_2",
                  "status": 0,
                  "description": "조치 실패: SSH 설정 변경 또는 재시작 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_01_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_01_2",
                "section": "[조치 결과]",
                "title": "[U_01_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - sshd_config 문법 에러 등 확인 필요"
              }