- name: "[U_02] Remediate Password Complexity Configuration"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    # 진단 스크립트는 'U_02_1' 하나만 던지지만, 조치 시 OS별로 로그 ID를 분기합니다.
    flag_list: []
    
    flag_id_main: "U_02"
    category: "account"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [RedHat 계열] Rocky, CentOS 등 -> Log ID: U_02_1
    # =========================================================
    - name: "[U_02_1] RedHat Password Policy Remediation"
      when: 
        - "'U_02_1' in flag_list"
        - ansible_os_family == 'RedHat'
      block:
        # 1-1. /etc/login.defs 수정
        - name: "[RedHat] Configure PASS_MAX_DAYS in login.defs"
          lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_MAX_DAYS'
            line: 'PASS_MAX_DAYS   90'
            state: present

        - name: "[RedHat] Configure PASS_MIN_DAYS in login.defs"
          lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_MIN_DAYS'
            line: 'PASS_MIN_DAYS   1'
            state: present

        # 1-2. /etc/security/pwquality.conf 수정
        - name: "[RedHat] Configure pwquality.conf"
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: "^{{ item.key }}"
            line: "{{ item.key }} = {{ item.value }}"
            state: present
          loop:
            - { key: 'minlen', value: '8' }
            - { key: 'dcredit', value: '-1' }
            - { key: 'ucredit', value: '-1' }
            - { key: 'lcredit', value: '-1' }
            - { key: 'ocredit', value: '-1' }

        - name: "[RedHat] Enable enforce_for_root in pwquality.conf"
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^#?enforce_for_root'
            line: 'enforce_for_root'
            state: present

        # 1-3. /etc/security/pwhistory.conf 수정 (기억 4회)
        - name: "[RedHat] Configure pwhistory.conf"
          lineinfile:
            path: /etc/security/pwhistory.conf
            regexp: '^#?remember'
            line: 'remember = 4'
            state: present
            create: yes

        # [성공 로그: U_02_1]
        - name: "Log U_02_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_02_1",
                  "status": 2,
                  "description": "[RedHat] 패스워드 정책(복잡성, 기간, 기억) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_02_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_02_1",
                "section": "[조치 결과]",
                "title": "[RedHat] 패스워드 정책 적용 성공",
                "cmd": "login.defs, pwquality.conf, pwhistory.conf 수정 완료",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: U_02_1]
      rescue:
        - name: "Log U_02_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_02_1",
                  "status": 0,
                  "description": "[RedHat] 조치 실패: 패스워드 설정 파일 수정 중 에러",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_02_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_02_1",
                "section": "[조치 결과]",
                "title": "[RedHat] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }


    # =========================================================
    # 2. [Debian 계열] Ubuntu 등 -> Log ID: U_02_2
    # =========================================================
    - name: "[U_02_2] Debian Password Policy Remediation"
      when: 
        - "'U_02_1' in flag_list"
        - ansible_os_family == 'Debian'
      block:
        # 2-1. /etc/login.defs 수정
        - name: "[Debian] Configure PASS_MAX_DAYS in login.defs"
          lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_MAX_DAYS'
            line: 'PASS_MAX_DAYS   90'
            state: present

        - name: "[Debian] Configure PASS_MIN_DAYS in login.defs"
          lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_MIN_DAYS'
            line: 'PASS_MIN_DAYS   1'
            state: present

        # 2-2. /etc/security/pwquality.conf 수정
        # Ubuntu는 common-password가 pwquality.conf 설정을 참조하도록 되어 있음
        - name: "[Debian] Configure pwquality.conf"
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: "^{{ item.key }}"
            line: "{{ item.key }} = {{ item.value }}"
            state: present
            create: yes
          loop:
            - { key: 'minlen', value: '8' }
            - { key: 'dcredit', value: '-1' }
            - { key: 'ucredit', value: '-1' }
            - { key: 'lcredit', value: '-1' }
            - { key: 'ocredit', value: '-1' }
        
        - name: "[Debian] Enable enforce_for_root in pwquality.conf"
          lineinfile:
            path: /etc/security/pwquality.conf
            regexp: '^#?enforce_for_root'
            line: 'enforce_for_root'
            state: present

        # [성공 로그: U_02_2]
        - name: "Log U_02_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_02_2",
                  "status": 2,
                  "description": "[Debian] 패스워드 정책(복잡성, 기간) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_02_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_02_2",
                "section": "[조치 결과]",
                "title": "[Debian] 패스워드 정책 적용 성공",
                "cmd": "login.defs, pwquality.conf 수정 완료",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: U_02_2]
      rescue:
        - name: "Log U_02_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_02_2",
                  "status": 0,
                  "description": "[Debian] 조치 실패: 패스워드 설정 파일 수정 중 에러",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_02_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_02_2",
                "section": "[조치 결과]",
                "title": "[Debian] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }