- name: "[U_03] Remediate Account Lockout Threshold"
  hosts: all
  become: yes
  vars:
    flag_list: []
    flag_id_main: "U_03"
    category: "account"
    
    # 공통 정책 값
    deny_count: 10
    unlock_time: 120

    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # [RedHat] 1. U_03_1 : pam_tally / pam_tally2 설정
    # =========================================================
    - name: "[U_03_1] RedHat pam_tally2 Remediation"
      when: 
        - "'U_03_1' in flag_list"
        - ansible_os_family == 'RedHat'
      block:
        - name: "Configure pam_tally2 in system-auth"
          lineinfile:
            path: /etc/pam.d/system-auth
            insertafter: '^auth'
            line: "auth required pam_tally2.so deny={{ deny_count }} unlock_time={{ unlock_time }} no_magic_root"
          register: r_u03_1
        
        - name: "Log Success U_03_1"
          include_tasks: log_helper.yml # 아래 로그 기록 로직과 동일 (지면상 축약 가능)
          vars: { f_id: "U_03_1", status: 2, desc: "RedHat pam_tally2 설정 완료" }
      rescue:
        - name: "Log Failure U_03_1"
          include_tasks: log_helper.yml
          vars: { f_id: "U_03_1", status: 0, desc: "RedHat pam_tally2 설정 실패" }

    # =========================================================
    # [RedHat] 2. U_03_2 : pam_faillock (Manual config)
    # =========================================================
    - name: "[U_03_2] RedHat pam_faillock Remediation"
      when: 
        - "'U_03_2' in flag_list"
        - ansible_os_family == 'RedHat'
      block:
        - name: "Update pam_faillock in system-auth"
          replace:
            path: /etc/pam.d/system-auth
            regexp: 'pam_faillock\.so.*deny=\d+'
            replace: "pam_faillock.so preauth silent audit deny={{ deny_count }} unlock_time={{ unlock_time }}"
          register: r_u03_2
        
        - name: "Log Success U_03_2"
          shell: "echo success" # 실제 구현시 상단 로그 양식 적용
      rescue:
        - name: "Log Failure U_03_2"
          shell: "echo fail"

    # =========================================================
    # [RedHat] 3. U_03_3 : authselect (권장 방식)
    # =========================================================
    - name: "[U_03_3] RedHat authselect faillock Remediation"
      when: 
        - "'U_03_3' in flag_list"
        - ansible_os_family == 'RedHat'
      block:
        - name: "Enable faillock via authselect"
          command: "authselect enable-feature with-faillock"
        
        - name: "Configure faillock.conf"
          lineinfile:
            path: /etc/security/faillock.conf
            regexp: "^{{ item.key }}"
            line: "{{ item.key }} = {{ item.value }}"
          loop:
            - { key: 'deny', value: "{{ deny_count }}" }
            - { key: 'unlock_time', value: "{{ unlock_time }}" }
            - { key: 'silent', value: '' }

        - name: "Log Success U_03_3 (JSON)"
          delegate_to: localhost
          become: false
          lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            line: '{"result": {"flag_id": "U_03_3", "status": 2, "description": "authselect faillock 활성화 및 정책 설정 완료"}}'
      rescue:
        - name: "Log Failure U_03_3"
          shell: "echo fail"

    # =========================================================
    # [Debian] 4. U_03_4 : pam_tally / pam_tally2 설정
    # =========================================================
    - name: "[U_03_4] Debian pam_tally2 Remediation"
      when: 
        - "'U_03_1' in flag_list" # 진단시 tally 플래그가 오면 Debian일 경우 4번으로 처리
        - ansible_os_family == 'Debian'
      block:
        - name: "Configure pam_tally2 in common-auth"
          lineinfile:
            path: /etc/pam.d/common-auth
            line: "auth required pam_tally2.so deny={{ deny_count }} unlock_time={{ unlock_time }}"
        
        - name: "Log Success U_03_4"
          shell: "echo success"
      rescue:
        - name: "Log Failure U_03_4"
          shell: "echo fail"

    # =========================================================
    # [Debian] 5. U_03_5 : pam_faillock (Ubuntu 표준)
    # =========================================================
    - name: "[U_03_5] Debian pam_faillock Remediation"
      when: 
        - "'U_03_3' in flag_list" # 진단시 faillock 플래그가 오면 Debian일 경우 5번으로 처리
        - ansible_os_family == 'Debian'
      block:
        # Ubuntu 24.04는 기본적으로 faillock이 설치되어 있으나 설정이 필요함
        - name: "Configure pam_faillock in common-auth"
          lineinfile:
            path: /etc/pam.d/common-auth
            line: "auth required pam_faillock.so preauth silent audit deny={{ deny_count }} unlock_time={{ unlock_time }}"
        
        - name: "Log Success U_03_5"
          delegate_to: localhost
          become: false
          lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            line: '{"result": {"flag_id": "U_03_5", "status": 2, "description": "Ubuntu pam_faillock 설정 완료"}}'
      rescue:
        - name: "Log Failure U_03_5"
          shell: "echo fail"