- name: "[U_06] Remediate su Command Restriction"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_06"
    category: "account"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_06_1] PAM 미사용 시 (파일 권한/그룹 설정)
    # - /usr/bin/su의 그룹을 wheel로 변경
    # - 권한을 4750(SUID + Group 실행 가능 + Other 권한 없음)으로 변경
    # =========================================================
    - name: "[U_06_1] Configure /usr/bin/su permissions"
      when: "'U_06_1' in flag_list"
      block:
        # 1-1. wheel 그룹 존재 여부 확인 및 생성
        - name: "[U_06_1] Ensure wheel group exists"
          group:
            name: wheel
            state: present

        # 1-2. /usr/bin/su 권한 및 그룹 변경
        - name: "[U_06_1] Change ownership and permissions of su"
          file:
            path: /usr/bin/su
            group: wheel
            mode: '4750'
          register: r_su_perm

        # 1-3. [Control Node] 로그 기록 (STDERR)
        - name: "Log U_06_1 Result (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_06_1",
                "section": "[조치 내용]",
                "title": "[U_06_1] su 명령어 파일 권한/그룹 변경",
                "cmd": "chgrp wheel /usr/bin/su && chmod 4750 /usr/bin/su",
                "result": "조치 성공 (그룹: wheel, 권한: 4750 설정 완료)"
              }

        # 1-4. [Control Node] JSON 기록 (STDOUT)
        - name: "Log U_06_1 Result (JSON File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_06_1",
                  "status": 2,
                  "description": "su 명령어 파일 권한 제한(4750, wheel) 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_06_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_06_1",
                  "status": 0,
                  "description": "조치 실패: su 파일 권한 변경 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_06_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_06_1",
                "section": "[조치 결과]",
                "title": "[U_06_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 시스템 권한 확인 필요"
              }


    # =========================================================
    # 2. [U_06_2] PAM 이용 시 (PAM 설정 점검)
    # - /etc/pam.d/su 파일에서 pam_wheel.so 활성화
    # =========================================================
    - name: "[U_06_2] Configure /etc/pam.d/su"
      when: "'U_06_2' in flag_list"
      block:
        # 2-1. wheel 그룹 존재 여부 확인 (PAM 설정의 전제조건)
        - name: "[U_06_2] Ensure wheel group exists"
          group:
            name: wheel
            state: present

        # 2-2. /etc/pam.d/su 설정 변경
        # 주석 처리된 라인이 있으면 주석 해제, 없으면 파일 상단(auth sufficient pam_rootok.so 다음)에 추가
        # 가이드: auth required pam_wheel.so use_uid
        - name: "[U_06_2] Enable pam_wheel.so in /etc/pam.d/su"
          replace:
            path: /etc/pam.d/su
            # 주석(#)이 있거나 없거나, auth required pam_wheel.so ... 패턴을 찾음
            regexp: '^#?\s*(auth\s+required\s+pam_wheel\.so\s+use_uid.*)$'
            replace: '\1'
          register: r_pam_su

        # 만약 위 replace로 변경되지 않았다면(라인 자체가 없었다면), 라인을 추가해야 함
        # 하지만 대부분의 배포판에는 주석 처리된 라인이 존재하므로 replace로 충분할 가능성이 높음
        # 안전을 위해 replace가 변경되지 않았고, 해당 설정이 없을 경우 추가하는 로직은 복잡도를 높이므로
        # 여기서는 replace(Uncomment) 방식에 집중합니다. (대부분의 Linux 기본 설정 대응)

        # 2-3. [Control Node] 로그 기록 (STDERR)
        - name: "Log U_06_2 Result (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_06_2",
                "section": "[조치 내용]",
                "title": "[U_06_2] PAM 설정 변경 (pam_wheel.so 활성화)",
                "cmd": "Uncomment 'auth required pam_wheel.so use_uid' in /etc/pam.d/su",
                "result": "조치 성공 (PAM을 통한 wheel 그룹 제한 설정 완료)"
              }

        # 2-4. [Control Node] JSON 기록 (STDOUT)
        - name: "Log U_06_2 Result (JSON File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_06_2",
                  "status": 2,
                  "description": "PAM 설정(pam_wheel.so)을 통한 su 제한 적용 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_06_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_06_2",
                  "status": 0,
                  "description": "조치 실패: PAM 설정 파일 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_06_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_06_2",
                "section": "[조치 결과]",
                "title": "[U_06_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - /etc/pam.d/su 파일 존재 여부 확인 필요"
              }