- name: "[U_36] Disable r-command Services (rsh, rlogin, rexec)"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_36"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_36_1] inetd.conf 조치 (rsh, rlogin, rexec 주석 처리)
    # =========================================================
    - name: "[U_36_1] Disable r-commands in /etc/inetd.conf"
      when: "'U_36_1' in flag_list"
      block:
        # 1-1. 설정 파일 수정 (shell, login, exec, rsh, rlogin, rexec 포함 라인 주석 처리)
        - name: "[U_36_1] Comment out r-commands in inetd.conf"
          replace:
            path: /etc/inetd.conf
            regexp: '^([[:space:]]*(shell|login|exec|rsh|rlogin|rexec)[[:space:]].*)$'
            replace: '# \1'
          register: r_inetd_rcmd

        # 1-2. inetd 서비스 재시작
        - name: "[U_36_1] Restart inetd service"
          service:
            name: inetd
            state: restarted
          when: r_inetd_rcmd.changed
          ignore_errors: yes

        # 1-3. [Control Node] 로그 기록
        - name: "Log U_36_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_36_1",
                "section": "[조치 결과]",
                "title": "[U_36_1] inetd.conf 내 r-command 비활성화 성공",
                "cmd": "Comment out rsh/rlogin/rexec in /etc/inetd.conf",
                "result": "조치 성공 (status: 2)"
              }

        # 1-4. [Control Node] JSON 기록
        - name: "Log U_36_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_36_1",
                  "status": 2,
                  "description": "inetd.conf 파일 내 r-command 서비스 주석 처리 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_36_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_36_1",
                  "status": 0,
                  "description": "조치 실패: inetd.conf 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_36_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_36_1",
                "section": "[조치 결과]",
                "title": "[U_36_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 존재 여부 확인 필요"
              }


    # =========================================================
    # 2. [U_36_2] xinetd 설정 조치 (rsh, rlogin, rexec)
    # =========================================================
    - name: "[U_36_2] Disable r-commands in xinetd"
      when: "'U_36_2' in flag_list"
      block:
        # 2-1. 대상 파일 확인 (rsh, rlogin, rexec)
        - name: "[U_36_2] Check xinetd files"
          stat:
            path: "/etc/xinetd.d/{{ item }}"
          loop:
            - rsh
            - rlogin
            - rexec
            - shell
            - login
            - exec
          register: r_xinetd_files

        # 2-2. 존재하는 파일에 대해 disable = yes 설정
        - name: "[U_36_2] Set disable=yes for existing files"
          lineinfile:
            path: "{{ item.stat.path }}"
            regexp: '^[[:space:]]*disable[[:space:]]*='
            line: '        disable = yes'
            state: present
          loop: "{{ r_xinetd_files.results }}"
          when: item.stat.exists
          register: r_xinetd_rcmd

        # 2-3. xinetd 서비스 재시작
        - name: "[U_36_2] Restart xinetd service"
          service:
            name: xinetd
            state: restarted
          when: r_xinetd_rcmd.changed
          ignore_errors: yes

        # 2-4. [Control Node] 로그 기록
        - name: "Log U_36_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_36_2",
                "section": "[조치 결과]",
                "title": "[U_36_2] xinetd r-command 비활성화 성공",
                "cmd": "Update /etc/xinetd.d/* (disable = yes)",
                "result": "조치 성공 (status: 2)"
              }

        # 2-5. [Control Node] JSON 기록
        - name: "Log U_36_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_36_2",
                  "status": 2,
                  "description": "xinetd r-command 설정 변경(disable=yes) 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_36_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_36_2",
                  "status": 0,
                  "description": "조치 실패: xinetd 설정 파일 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_36_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_36_2",
                "section": "[조치 결과]",
                "title": "[U_36_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 권한 확인 필요"
              }


    # =========================================================
    # 3. [U_36_3] Systemd 서비스 중지 (rsh, rlogin, rexec)
    # =========================================================
    - name: "[U_36_3] Stop r-command Systemd Services"
      when: "'U_36_3' in flag_list"
      block:
        # 3-1. 서비스 중지 및 비활성화
        # rsh-server, rlogin-server 등 다양한 이름이 있을 수 있으나 가이드 기준(rsh, rlogin, rexec)
        - name: "[U_36_3] Stop r-command services"
          service:
            name: "{{ item }}"
            state: stopped
            enabled: no
          loop:
            - rsh.socket
            - rlogin.socket
            - rexec.socket
            - rsh.service
            - rlogin.service
            - rexec.service
          ignore_errors: yes

        # 3-2. [Control Node] 로그 기록
        - name: "Log U_36_3 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_36_3",
                "section": "[조치 결과]",
                "title": "[U_36_3] r-command Systemd 서비스 중지 성공",
                "cmd": "systemctl stop/disable rsh, rlogin, rexec",
                "result": "조치 성공 (status: 2)"
              }

        # 3-3. [Control Node] JSON 기록
        - name: "Log U_36_3 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_36_3",
                  "status": 2,
                  "description": "r-command Systemd 서비스 중지 및 비활성화 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_36_3 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_36_3",
                  "status": 0,
                  "description": "조치 실패: 서비스 중지 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_36_3 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_36_3",
                "section": "[조치 결과]",
                "title": "[U_36_3] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }