- name: "[U_42] Disable Unnecessary RPC Services"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_42"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

    # 차단 대상 RPC 서비스 목록 (가이드 및 진단 스크립트 기준)
    rpc_services:
      - rpcbind
      - rpc.cmsd
      - rpc.ttdbserverd
      - sadmind
      - rusersd
      - walld
      - sprayd
      - rstatd
      - rpc.nisd
      - rexd
      - rpc.pcnfsd
      - rpc.statd
      - rpc.ypupdated
      - rpc.rquotad
      - kcms_server
      - cachefsd

  tasks:
    # =========================================================
    # 1. [U_42_1] inetd.conf 설정 조치
    # =========================================================
    - name: "[U_42_1] Disable RPC services in /etc/inetd.conf"
      when: "'U_42_1' in flag_list"
      block:
        # 1-1. 설정 파일 수정 (주석 처리)
        - name: "[U_42_1] Comment out RPC services in inetd.conf"
          replace:
            path: /etc/inetd.conf
            regexp: '^([[:space:]]*({{ rpc_services | join("|") }})[[:space:]].*)$'
            replace: '# \1'
          register: r_inetd_rpc

        # 1-2. inetd 서비스 재시작
        - name: "[U_42_1] Restart inetd service"
          service:
            name: inetd
            state: restarted
          when: r_inetd_rpc.changed
          ignore_errors: yes

        # 1-3. [Control Node] 로그 기록
        - name: "Log U_42_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_42_1",
                "section": "[조치 결과]",
                "title": "[U_42_1] inetd.conf 내 RPC 서비스 비활성화 성공",
                "cmd": "Comment out RPC services in /etc/inetd.conf",
                "result": "조치 성공 (status: 2)"
              }

        # 1-4. [Control Node] JSON 기록
        - name: "Log U_42_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_42_1",
                  "status": 2,
                  "description": "inetd.conf 파일 내 RPC 서비스 주석 처리 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_42_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_42_1",
                  "status": 0,
                  "description": "조치 실패: inetd.conf 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_42_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_42_1",
                "section": "[조치 결과]",
                "title": "[U_42_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 존재 여부 확인 필요"
              }


    # =========================================================
    # 2. [U_42_2] xinetd 설정 조치
    # =========================================================
    - name: "[U_42_2] Disable RPC services in xinetd"
      when: "'U_42_2' in flag_list"
      block:
        # 2-1. xinetd 서비스 파일 확인 (존재하는 파일만 골라냄)
        - name: "[U_42_2] Check xinetd service files"
          stat:
            path: "/etc/xinetd.d/{{ item }}"
          loop: "{{ rpc_services }}"
          register: r_xinetd_files

        # 2-2. 존재하는 파일에 대해 disable = yes 설정
        - name: "[U_42_2] Set disable=yes for existing RPC files"
          lineinfile:
            path: "{{ item.stat.path }}"
            regexp: '^[[:space:]]*disable[[:space:]]*='
            line: '        disable = yes'
            state: present
          loop: "{{ r_xinetd_files.results }}"
          when: item.stat.exists
          register: r_xinetd_rpc

        # 2-3. xinetd 서비스 재시작
        - name: "[U_42_2] Restart xinetd service"
          service:
            name: xinetd
            state: restarted
          when: r_xinetd_rpc.changed
          ignore_errors: yes

        # 2-4. [Control Node] 로그 기록
        - name: "Log U_42_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_42_2",
                "section": "[조치 결과]",
                "title": "[U_42_2] xinetd RPC 서비스 비활성화 성공",
                "cmd": "Update /etc/xinetd.d/* (disable = yes)",
                "result": "조치 성공 (status: 2)"
              }

        # 2-5. [Control Node] JSON 기록
        - name: "Log U_42_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_42_2",
                  "status": 2,
                  "description": "xinetd RPC 서비스 설정 변경(disable=yes) 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_42_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_42_2",
                  "status": 0,
                  "description": "조치 실패: xinetd 설정 파일 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_42_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_42_2",
                "section": "[조치 결과]",
                "title": "[U_42_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 권한 확인 필요"
              }


    # =========================================================
    # 3. [U_42_3] Systemd 서비스 중지 (rpcbind 등)
    # =========================================================
    - name: "[U_42_3] Stop RPC Systemd Services"
      when: "'U_42_3' in flag_list"
      block:
        # 3-1. 서비스 중지 및 비활성화 (주요 대상: rpcbind)
        - name: "[U_42_3] Stop RPC services"
          service:
            name: "{{ item }}"
            state: stopped
            enabled: no
          loop: "{{ rpc_services }}"
          # rpcbind는 소켓도 함께 내려야 할 수 있음
          ignore_errors: yes

        - name: "[U_42_3] Stop specific sockets (rpcbind.socket)"
          service:
            name: rpcbind.socket
            state: stopped
            enabled: no
          ignore_errors: yes

        # 3-2. [Control Node] 로그 기록
        - name: "Log U_42_3 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_42_3",
                "section": "[조치 결과]",
                "title": "[U_42_3] RPC Systemd 서비스 중지 성공",
                "cmd": "systemctl stop/disable rpcbind and others",
                "result": "조치 성공 (status: 2)"
              }

        # 3-3. [Control Node] JSON 기록
        - name: "Log U_42_3 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_42_3",
                  "status": 2,
                  "description": "RPC Systemd 서비스(rpcbind 등) 중지 및 비활성화 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_42_3 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_42_3",
                  "status": 0,
                  "description": "조치 실패: 서비스 중지 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_42_3 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_42_3",
                "section": "[조치 결과]",
                "title": "[U_42_3] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }