    ---
    - name: "U-55 | Remediate FTP Default Account Shell Restriction (Controlled Env, Logs-Only JSONL)"
      hosts: all
      become: yes
      gather_facts: no
    
      vars:
        FLAG_ID: "U-55"
    
        # 조치 대상/기준 (sh 로직과 동일)
        ftp_user: "ftp"
        allowed_shells:
          - "/bin/false"
          - "/sbin/nologin"
          - "/usr/sbin/nologin"
    
        # 조치 값(통일): ftp 계정 쉘을 /bin/false 로 고정
        remediate_shell: "/bin/false"
    
        # 팀 로그 규칙(고정)
        LOG_SECTION_STEP: "[조치 내용]"
        LOG_SECTION_BASIS: "[조치 결과]"
        LOG_TITLE_BASIS: "조치 근거"
        LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"
    
      tasks:
        # ---------------------------------------------------------
        # (공통) 변수 기본값(미정의 방지)
        # ---------------------------------------------------------
        - name: "U-55 | init defaults"
          ansible.builtin.set_fact:
            r_getent: {}
            r_current_shell: {}
            current_shell: ""
            r_usermod: {}
          changed_when: false
    
        # =========================================================
        # Step 1) ftp 계정 존재 여부 확인 (getent)
        # =========================================================
        - name: "U-55 | [U_55_1] ftp 계정 조회(getent)"
          ansible.builtin.command: "getent passwd {{ ftp_user }}"
          register: r_getent
          changed_when: false
          failed_when: false
    
        - name: "U-55 | [U_55_1] ts (account check)"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_551_a
          changed_when: false
    
        - name: "U-55 | [U_55_1] LOG step (account exists) JSONL"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_551_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_55_1] ftp 계정 존재 여부",
                  "cmd": "getent passwd " ~ ftp_user,
                  "result": ((r_getent.rc | default(1)) == 0) | ternary("계정 존재", "계정 없음")
                } | to_json
              }}
          changed_when: false
    
        # =========================================================
        # Step 2) ftp 쉘 확인 (getent | awk -F: '{print $7}')
        # =========================================================
        - name: "U-55 | [U_55_1] ftp 쉘 필드 추출"
          ansible.builtin.shell: "getent passwd {{ ftp_user }} | awk -F: '{print $7}'"
          args:
            executable: /bin/bash
          register: r_current_shell
          changed_when: false
          failed_when: false
          when: (r_getent.rc | default(1)) == 0
    
        - name: "U-55 | [U_55_1] set current_shell(trim)"
          ansible.builtin.set_fact:
            current_shell: "{{ (r_current_shell.stdout | default('') | trim) }}"
          changed_when: false
          when: (r_getent.rc | default(1)) == 0
    
        - name: "U-55 | [U_55_1] ts (shell check)"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_551_b
          changed_when: false
    
        - name: "U-55 | [U_55_1] LOG step (current shell) JSONL"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_551_b.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_55_1] ftp 계정 로그인 쉘 확인",
                  "cmd": "getent passwd " ~ ftp_user ~ " | awk -F: '{print $7}'",
                  "result": (
                    ((r_getent.rc | default(1)) == 0)
                    | ternary("shell=" ~ (current_shell | default("<empty>")), "shell=<no_ftp_account>")
                  )
                } | to_json
              }}
          changed_when: false
    
        # =========================================================
        # Step 3) 조치: 허용 쉘이 아니면 usermod로 /bin/false로 변경
        # =========================================================
        - name: "U-55 | [U_55_1] ftp 쉘을 {{ remediate_shell }} 로 변경(usermod)"
          ansible.builtin.command: "usermod -s {{ remediate_shell }} {{ ftp_user }}"
          register: r_usermod
          changed_when: (r_usermod.rc | default(1)) == 0
          failed_when: false
          when:
            - (r_getent.rc | default(1)) == 0
            - (current_shell | default("")) not in allowed_shells
    
        - name: "U-55 | [U_55_1] ts (remediation)"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_551_c
          changed_when: false
    
        - name: "U-55 | [U_55_1] LOG step (usermod remediation) JSONL"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_551_c.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_55_1] ftp 계정 쉘 제한 적용",
                  "cmd": "usermod -s " ~ remediate_shell ~ " " ~ ftp_user,
                  "result": (
                    ((r_getent.rc | default(1)) != 0) | ternary(
                      "skipped: ftp 계정 없음",
                      (
                        ((current_shell | default("")) in allowed_shells)
                        | ternary(
                          "skipped: 이미 로그인 불가 쉘(" ~ (current_shell | default("<empty>")) ~ ")",
                          "attempted=True, rc=" ~ (r_usermod.rc | default(0) | string)
                          ~ ", failed=" ~ (((r_usermod.failed | default(false)) | bool) | string)
                          ~ ", msg=" ~ ((r_usermod.msg | default("") | string) | truncate(160, True, "..."))
                        )
                      )
                    )
                  )
                } | to_json
              }}
          changed_when: false
    
        # =========================================================
        # Step 4) 조치 결과(근거) 1줄
        # - usermod 실패 시: status=info (구체 사유)
        # =========================================================
        - name: "U-55 | [U_55_1] ts (basis)"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_551_d
          changed_when: false
    
        - name: "U-55 | [U_55_1] LOG basis (remediation basis) JSONL"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_551_d.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    ((r_getent.rc | default(1)) != 0)
                    | ternary(
                      "[U_55_1] ftp 계정 미존재: 서비스 미사용/미설치 또는 표준 계정 미구성 가능 — 조치 불필요(양호)",
                      (
                        ((current_shell | default("")) in allowed_shells)
                        | ternary(
                          "[U_55_1] ftp 계정 쉘이 이미 로그인 불가 쉘로 설정됨(조치 불필요): " ~ (current_shell | default("<empty>")),
                          (
                            ((r_usermod.rc | default(1)) == 0)
                            | ternary(
                              "[U_55_1] ftp 계정에 로그인 가능한 쉘이 부여되어 있어 " ~ remediate_shell ~ " 로 변경 적용(조치 수행): before=" ~ (current_shell | default("<empty>")),
                              "[U_55_1] ftp 계정 쉘 변경(usermod) 시도했으나 실패: 정책/권한/계정잠금 등으로 변경 불가 가능 — 담당자 확인 필요(info): before=" ~ (current_shell | default("<empty>"))
                            )
                          )
                        )
                      )
                    )
                  ),
                  "status": (
                    ((r_getent.rc | default(1)) != 0)
                    | ternary(
                      "양호",
                      (
                        ((current_shell | default("")) in allowed_shells)
                        | ternary(
                          "양호",
                          (
                            ((r_usermod.rc | default(1)) == 0)
                            | ternary("취약", "info")
                          )
                        )
                      )
                    )
                  )
                } | to_json
              }}
          changed_when: false
    
        # ---------------------------------------------------------
        # (블록 말미) summary 로그(팀 규칙 반영)
        # ---------------------------------------------------------
        - name: "U-55 | [U_55_1] summary LOG(JSONL)"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_551_s
              changed_when: false
    