    ---
    - name: "U-58 | Remediate Unnecessary SNMP Service (Controlled Env, Logs-Only JSONL)"
      hosts: all
      become: yes
      gather_facts: no
    
      vars:
        FLAG_ID: "U-58"
    
        # ===== 팀 로그 템플릿(고정) =====
        LOG_SECTION_STEP: "[조치 내용]"
        LOG_SECTION_BASIS: "[조치 결과]"
        LOG_TITLE_BASIS: "조치 근거"
        LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"
    
        # ===== 타겟 =====
        SNMPD_SERVICE: "snmpd"
    
      tasks:
        # ---------------------------------------------------------
        # (공통) 미정의 방지
        # ---------------------------------------------------------
        - name: "U-58 | init defaults"
          ansible.builtin.set_fact:
            snmpd_unit_exists: "NO"
            snmpd_is_active: "NO"
            snmpd_proc_exists: "NO"
            r_snmpd_stopdisable: {}
          changed_when: false
    
        # =========================================================
        # U_58_1 : SNMP 서비스(snmpd) 활성/실행 여부 확인 + stop/disable
        # - unit 존재하면: stop+disable 자동조치
        # - unit 미존재인데 프로세스가 있으면: 수동 기동/비표준 실행 가능 → 자동조치 금지(info)
        # =========================================================
    
        - name: "U-58 | [U_58_1] detect snmpd.service unit"
          ansible.builtin.shell: |
            systemctl list-unit-files --type=service 2>/dev/null | awk '{print $1}' | grep -qx "{{ SNMPD_SERVICE }}.service" && echo "YES" || echo "NO"
          args:
            executable: /bin/bash
          register: r_unit
          changed_when: false
          failed_when: false
    
        - name: "U-58 | set snmpd_unit_exists"
          ansible.builtin.set_fact:
            snmpd_unit_exists: "{{ (r_unit.stdout | default('NO')) }}"
          changed_when: false
    
        - name: "U-58 | [U_58_1] check snmpd is-active (when unit exists)"
          ansible.builtin.shell: |
            systemctl is-active "{{ SNMPD_SERVICE }}" >/dev/null 2>&1 && echo "YES" || echo "NO"
          args:
            executable: /bin/bash
          register: r_active
          changed_when: false
          failed_when: false
          when: snmpd_unit_exists == "YES"
    
        - name: "U-58 | set snmpd_is_active"
          ansible.builtin.set_fact:
            snmpd_is_active: "{{ (r_active.stdout | default('NO')) }}"
          changed_when: false
          when: snmpd_unit_exists == "YES"
    
        - name: "U-58 | [U_58_1] check snmpd process exists (fallback)"
          ansible.builtin.shell: |
            ps -ef 2>/dev/null | grep -v grep | grep -q "[s]nmpd" && echo "YES" || echo "NO"
          args:
            executable: /bin/bash
          register: r_proc
          changed_when: false
          failed_when: false
    
        - name: "U-58 | set snmpd_proc_exists"
          ansible.builtin.set_fact:
            snmpd_proc_exists: "{{ (r_proc.stdout | default('NO')) }}"
          changed_when: false
    
        - name: "U-58 | [U_58_1] ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_581_a
          changed_when: false
    
        - name: "U-58 | [U_58_1] LOG step (status detect) JSONL"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_581_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_58_1] SNMP(snmpd) 서비스/프로세스 상태 확인",
                  "cmd": "unit=" ~ SNMPD_SERVICE ~ ".service 존재여부 + systemctl is-active + ps -ef",
                  "result": "unit_exists=" ~ (snmpd_unit_exists | default("NO"))
                            ~ ", is_active=" ~ (snmpd_is_active | default("NO"))
                            ~ ", proc_exists=" ~ (snmpd_proc_exists | default("NO"))
                } | to_json
              }}
          changed_when: false
    
        - name: "U-58 | [U_58_1] snmpd stop+disable (when unit exists)"
          ansible.builtin.systemd:
            name: "{{ SNMPD_SERVICE }}"
            state: stopped
            enabled: false
          register: r_snmpd_stopdisable
          failed_when: false
          when: snmpd_unit_exists == "YES"
    
        - name: "U-58 | [U_58_1] LOG step (stop+disable) JSONL"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_581_b
              changed_when: false
    
            - name: "LOG step"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_581_b.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_STEP,
                      "title": "[U_58_1] SNMP(snmpd) 중지 및 비활성화",
                      "cmd": "systemd: name=" ~ SNMPD_SERVICE ~ " state=stopped enabled=false",
                      "result": "changed=" ~ (((r_snmpd_stopdisable.changed | default(false)) | bool) | string)
                                ~ ", failed=" ~ (((r_snmpd_stopdisable.failed | default(false)) | bool) | string)
                                ~ ", msg=" ~ ((r_snmpd_stopdisable.msg | default("") | string) | truncate(160, True, "..."))
                    } | to_json
                  }}
              changed_when: false
          when: snmpd_unit_exists == "YES"
    
        - name: "U-58 | [U_58_1] LOG basis (unit exists) JSONL"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_581_c
              changed_when: false
    
            - name: "LOG basis"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_581_c.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_BASIS,
                      "title": LOG_TITLE_BASIS,
                      "basis": (
                        "[U_58_1] snmpd.service 존재 환경: 불필요 SNMP 서비스 차단을 위해 stop+disable "
                        ~ ((((r_snmpd_stopdisable.changed | default(false)) | bool)
                            | ternary("기준 미충족 상태를 교정 적용(조치 수행)", "이미 중지/비활성 상태로 변경 불필요(조치 불필요)")))
                        ~ "; 실행 실패여부="
                        ~ ((((r_snmpd_stopdisable.failed | default(false)) | bool) | ternary("YES","NO")))
                      ),
                      "status": (((r_snmpd_stopdisable.changed | default(false)) | bool) | ternary("취약", "양호"))
                    } | to_json
                  }}
              changed_when: false
          when: snmpd_unit_exists == "YES"
    
        - name: "U-58 | [U_58_1] LOG basis (unit missing) JSONL"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_581_na
              changed_when: false
    
            - name: "LOG basis"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_581_na.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_BASIS,
                      "title": LOG_TITLE_BASIS,
                      "basis": (
                        (snmpd_proc_exists | default("NO")) == "YES"
                        | ternary(
                            "[U_58_1] snmpd.service 유닛 미존재인데 snmpd 프로세스가 실행 중: 수동 기동/비표준 실행(컨테이너/스크립트/직접 실행) 가능 — systemd stop+disable 대상 부재로 자동조치 금지(info) — 담당자 확인 필요",
                            "[U_58_1] snmpd.service 유닛 미존재 및 snmpd 프로세스 미탐지: 패키지 미설치/서비스 미사용 또는 배포 표준 비대상 가능 — 조치 불필요(양호)"
                          )
                      ),
                      "status": (
                        (snmpd_proc_exists | default("NO")) == "YES"
                        | ternary("info", "양호")
                      )
                    } | to_json
                  }}
              changed_when: false
          when: snmpd_unit_exists != "YES"
    
        - name: "U-58 | [U_58_1] summary LOG(JSONL)"
          block:
            - name: "ts"
              ansible.builtin.command: "{{ LOG_TS_CMD }}"
              register: ts_581_s
              changed_when: false
    
            - name: "LOG step"
              ansible.builtin.debug:
                msg: >-
                  {{
                    {
                      "ts": (ts_581_s.stdout | default("")),
                      "flag_id": FLAG_ID,
                      "section": LOG_SECTION_STEP,
                      "title": "[U_58_1] summary",
                      "cmd": "snmpd: detect unit/active/process + optional stop/disable",
                      "result": "unit_exists=" ~ (snmpd_unit_exists | default("NO"))
                                ~ ", is_active=" ~ (snmpd_is_active | default("NO"))
                                ~ ", proc_exists=" ~ (snmpd_proc_exists | default("NO"))
                                ~ ", changed=" ~ ((((r_snmpd_stopdisable.changed | default(false)) | bool) | string))
                                ~ ", failed=" ~ ((((r_snmpd_stopdisable.failed | default(false)) | bool) | string))
                    } | to_json
                  }}
              changed_when: false