- name: "U_58 | Remediate Unnecessary SNMP Service (Controlled Env, Logs+JSON to /tmp, Stream-Split, UTF8-safe, Host-Split)"
  hosts: all
  become: yes
  gather_facts: no

  vars:
    FLAG_ID: "U_58"

    # 대상 서비스명 (systemd)
    snmp_service: "snmpd"

    # ===== timestamp formats =====
    TS_STDERR_CMD: "date -u +%Y-%m-%dT%H:%M:%SZ"
    TS_STDOUT_CMD: "date +%Y_%m_%d' / '%H:%M:%S"

    # ==============================
    # [팀 조건] 로그/JSON 경로 및 파일명 규칙 (호스트별 분리 + scan 제거)
    # ==============================
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    FILE_HOST: "{{ inventory_hostname | regex_replace('(-scan)$', '') }}"
    my_log_file: "{{ log_dir }}/{{ FILE_HOST }}-remediate_{{ FLAG_ID }}.log"
    my_json_file: "{{ json_dir }}/{{ FILE_HOST }}-remediate_{{ FLAG_ID }}.json"

  tasks:
    # ---------------------------------------------------------
    # (공통) 미정의 방지 (status/desc/result/cmd 포함)
    # ---------------------------------------------------------
    - name: "U_58 | init defaults"
      ansible.builtin.set_fact:
        r_snmp_active: {}
        r_snmp_enabled: {}
        r_snmp_stop: {}
        r_snmp_disable: {}

        u581_cmd: ""
        u581_status: 0
        u581_desc: ""
        u581_result: ""
      changed_when: false

    # ---------------------------------------------------------
    # (공통) meta 수집 (stdout JSON meta용)
    # ---------------------------------------------------------
    - name: "U_58 | meta | hostname"
      ansible.builtin.command: "hostname"
      register: m_host
      changed_when: false

    - name: "U_58 | meta | ip"
      ansible.builtin.shell: "hostname -I | awk '{print $1}'"
      register: m_ip
      changed_when: false

    - name: "U_58 | meta | user"
      ansible.builtin.command: "whoami"
      register: m_user
      changed_when: false

    - name: "U_58 | meta | set_fact"
      ansible.builtin.set_fact:
        META_HOSTNAME: "{{ m_host.stdout | default('') }}"
        META_IP: "{{ m_ip.stdout | default('') }}"
        META_USER: "{{ m_user.stdout | default('') }}"
      changed_when: false

    # =========================================================
    # U_58_1) 불필요한 SNMP 서비스(snmpd) 중지 및 비활성화
    # - 서비스 미존재/조회 불가이면 status=0 + 사유 기록
    # - inactive/disabled이면 status=2 + "불필요" 기록
    # - active/enabled이면 stop/disable 시도 후 status=2 기록(실패는 desc에 반영)
    # - 로그/JSON: controller(localhost)에 기록, UTF8-safe, 스트림 분리
    # =========================================================
    - name: "U_58 | [U_58_1] snmpd stop+disable + logs/json (UTF8-safe)"
      block:
        - name: "U_58_1 | check is-active snmpd"
          ansible.builtin.command: "systemctl is-active {{ snmp_service }}"
          register: r_snmp_active
          changed_when: false
          failed_when: false

        - name: "U_58_1 | check is-enabled snmpd"
          ansible.builtin.command: "systemctl is-enabled {{ snmp_service }}"
          register: r_snmp_enabled
          changed_when: false
          failed_when: false

        - name: "U_58_1 | stop snmpd (only when active)"
          ansible.builtin.systemd:
            name: "{{ snmp_service }}"
            state: stopped
          register: r_snmp_stop
          failed_when: false
          when: (r_snmp_active.stdout | default('')) == "active"

        - name: "U_58_1 | disable snmpd (only when enabled)"
          ansible.builtin.systemd:
            name: "{{ snmp_service }}"
            enabled: false
          register: r_snmp_disable
          failed_when: false
          when: (r_snmp_enabled.stdout | default('')) == "enabled"

        - name: "U_58_1 | compute | init"
          ansible.builtin.set_fact:
            u581_cmd: "systemctl is-active {{ snmp_service }}; systemctl is-enabled {{ snmp_service }}; (if active) systemctl stop {{ snmp_service }}; (if enabled) systemctl disable {{ snmp_service }}"
            u581_status: 0
            u581_desc: ""
          changed_when: false

        - name: "U_58_1 | compute | service missing or query failed"
          ansible.builtin.set_fact:
            u581_status: 0
            u581_desc: "snmpd 서비스가 존재하지 않거나 상태 조회가 불가하여 조치하지 않았습니다"
          changed_when: false
          when:
            - (r_snmp_active.rc | default(0) | int) != 0
            - (r_snmp_enabled.rc | default(0) | int) != 0

        - name: "U_58_1 | compute | already inactive/disabled"
          ansible.builtin.set_fact:
            u581_status: 2
            u581_desc: "snmpd 서비스가 이미 비활성/중지 상태여서 조치가 필요 없습니다"
          changed_when: false
          when:
            - not ((r_snmp_active.rc | default(0) | int) != 0 and (r_snmp_enabled.rc | default(0) | int) != 0)
            - (r_snmp_active.stdout | default('')) != "active"
            - (r_snmp_enabled.stdout | default('')) != "enabled"

        - name: "U_58_1 | compute | attempted stop/disable"
          ansible.builtin.set_fact:
            u581_status: 2
            u581_desc: >-
              {% set stop_failed = (r_snmp_stop.failed | default(false)) | bool %}
              {% set dis_failed  = (r_snmp_disable.failed | default(false)) | bool %}
              {% if stop_failed or dis_failed %}
              snmpd 서비스가 활성/사용 상태여서 중지/비활성화를 시도했으나 일부 작업이 실패했습니다(stop_failed={{ stop_failed }}, disable_failed={{ dis_failed }})
              {% else %}
              snmpd 서비스가 활성/사용 상태여서 중지/비활성화를 적용했습니다
              {% endif %}
          changed_when: false
          when:
            - not ((r_snmp_active.rc | default(0) | int) != 0 and (r_snmp_enabled.rc | default(0) | int) != 0)
            - ((r_snmp_active.stdout | default('')) == "active") or ((r_snmp_enabled.stdout | default('')) == "enabled")

        - name: "U_58_1 | compute | finalize result"
          ansible.builtin.set_fact:
            u581_result: "{{ ((u581_status | int) == 2) | ternary('조치 성공 (status: 2)', '조치 불가 (status: 0)') }}"
          changed_when: false

        - name: "U_58_1 | emit stderr log JSON (controller + stderr stream, UTF8-safe)"
          delegate_to: localhost
          become: false
          ansible.builtin.shell: |
            printf '%s\n' '{{ {
              "ts": (ts_581_e.stderr_ts | default("")),
              "flag_id": "U_58_1",
              "section": "SNMP(snmpd) 서비스 중지 및 비활성화",
              "title": "[U_58_1] SNMP(snmpd) 서비스 중지 및 비활성화",
              "cmd": u581_cmd,
              "result": u581_result
            } | to_json }}' \
            | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), ensure_ascii=False))' \
            | tee -a '{{ my_log_file }}' 1>&2
          vars:
            ts_581_e:
              stderr_ts: "{{ lookup('pipe', TS_STDERR_CMD) }}"
          changed_when: false

        - name: "U_58_1 | emit stdout result JSON (controller + stdout stream, UTF8-safe)"
          delegate_to: localhost
          become: false
          ansible.builtin.shell: |
            printf '%s\n' '{{ {
              "meta": {"hostname": META_HOSTNAME, "ip": META_IP, "user": META_USER},
              "result": {
                "flag_id": "U_58_1",
                "status": (u581_status | int),
                "description": u581_desc,
                "category": "service",
                "timestamp": (ts_581_o.stdout_ts | default(""))
              }
            } | to_json }}' \
            | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin), ensure_ascii=False))' \
            | tee -a '{{ my_json_file }}'
          vars:
            ts_581_o:
              stdout_ts: "{{ lookup('pipe', TS_STDOUT_CMD) }}"
          changed_when: false
      when:
        - "'U_58_1' in (flag_list | default([]))"
