---
- name: "U-03 | Account Lockout Threshold Configuration"
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    FLAG_ID: "U-03"
    
    # 설정 파일 경로
    faillock_conf: "/etc/security/faillock.conf"
    
    # PAM 파일 경로 (Ubuntu)
    pam_common_auth: "/etc/pam.d/common-auth"
    pam_common_account: "/etc/pam.d/common-account"

    # 로그 관련 변수
    LOG_SECTION_STEP: "[조치 내용]"
    LOG_SECTION_BASIS: "[조치 결과]"
    LOG_TITLE_BASIS: "조치 근거"
    LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"

  tasks:
    # ---------------------------------------------------------
    # (공통) 변수 초기화
    # ---------------------------------------------------------
    - name: "U-03 | init defaults"
      ansible.builtin.set_fact:
        r_authselect: {}
        r_faillock_conf: {}
        r_pam_ubuntu: {}
      changed_when: false

    # =========================================================
    # 1. Rocky Linux 9 조치 (authselect + faillock.conf)
    # =========================================================
    - name: "U-03 | [Rocky] authselect faillock 기능 활성화"
      ansible.builtin.command:
        cmd: "authselect enable-feature with-faillock"
      register: r_authselect
      # 이미 활성화된 경우 'No changes' 등의 메시지가 나오므로 changed 여부 판단 필요
      # authselect 명령은 변경사항이 없으면 exit code 0이지만 stdout으로 알려줌
      changed_when: "'No changes' not in r_authselect.stdout"
      when: ansible_os_family == "RedHat"

    - name: "U-03 | [Rocky] authselect apply changes"
      ansible.builtin.command:
        cmd: "authselect apply-changes"
      when: 
        - ansible_os_family == "RedHat"
        - r_authselect.changed
      changed_when: true

    # =========================================================
    # 2. Ubuntu 24.04 조치 (pam_faillock 존재 확인 + faillock.conf)
    #    Ubuntu 24.04는 기본적으로 faillock이 설치/설정되어 있음.
    #    PAM 파일을 직접 건드리는 것은 매우 위험하므로, faillock.conf 설정에 집중
    # =========================================================
    
    # Ubuntu의 경우 pam-auth-update 등을 통해 관리되므로, 
    # 기본적으로 common-auth에 pam_faillock이 있는지 확인만 하고 없으면 경고(Info) 처리
    # (강제로 넣다가 시스템 잠금 위험)
    - name: "U-03 | [Ubuntu] Check pam_faillock in common-auth"
      ansible.builtin.shell: "grep 'pam_faillock.so' {{ pam_common_auth }}"
      register: r_pam_check
      changed_when: false
      failed_when: false
      when: ansible_os_family == "Debian"

    # =========================================================
    # 3. 공통 조치: /etc/security/faillock.conf 설정
    #    deny = 10, unlock_time = 600
    # =========================================================
    - name: "U-03 | [Common] faillock.conf 설정 (deny=10)"
      ansible.builtin.lineinfile:
        path: "{{ faillock_conf }}"
        regexp: '^\s*#?\s*deny\s*='
        line: 'deny = 10'
        state: present
        create: yes # 파일이 없으면 생성
      register: r_faillock_deny
    
    - name: "U-03 | [Common] faillock.conf 설정 (unlock_time=600)"
      ansible.builtin.lineinfile:
        path: "{{ faillock_conf }}"
        regexp: '^\s*#?\s*unlock_time\s*='
        line: 'unlock_time = 600'
        state: present
      register: r_faillock_unlock

    # silent 옵션 활성화 (보안상 권장 - 로그인 실패 시 정보 노출 최소화)
    - name: "U-03 | [Common] faillock.conf 설정 (silent)"
      ansible.builtin.lineinfile:
        path: "{{ faillock_conf }}"
        regexp: '^\s*#?\s*silent'
        line: 'silent'
        state: present
      register: r_faillock_silent

    # =========================================================
    # 4. 결과 로깅
    # =========================================================
    - name: "U-03 | 조치 내용 상세 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_step
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_step.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "계정 잠금 임계값 설정 (deny=10, unlock_time=600)",
                  "cmd": "faillock.conf: deny=10 unlock_time=600 silent; (Rocky) authselect with-faillock",
                  "result": "Rocky_authselect=" ~ ((r_authselect.changed | default(false)) | bool | string) ~
                            ", deny_changed=" ~ ((r_faillock_deny.changed | default(false)) | bool | string) ~
                            ", unlock_changed=" ~ ((r_faillock_unlock.changed | default(false)) | bool | string)
                } | to_json
              }}
          changed_when: false

    - name: "U-03 | 최종 결과 근거 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_basis
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_basis.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    "계정 잠금 정책 " ~
                    (((r_authselect.changed | default(false)) or (r_faillock_deny.changed | default(false)) or (r_faillock_unlock.changed | default(false))) | ternary("설정됨", "이미 설정됨")) ~
                    " (임계값 10회, 잠금시간 600초)"
                  ),
                  "status": "양호"
                } | to_json
              }}
          changed_when: false