---
- name: "U-08 | Minimal Accounts in Root Group"
  hosts: all
  become: yes
  gather_facts: no

  vars:
    FLAG_ID: "U-08"

    # 로그 관련 변수
    LOG_SECTION_STEP: "[조치 내용]"
    LOG_SECTION_BASIS: "[조치 결과]"
    LOG_TITLE_BASIS: "조치 근거"
    LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"

  tasks:
    # ---------------------------------------------------------
    # (공통) 변수 초기화
    # ---------------------------------------------------------
    - name: "U-08 | init defaults"
      ansible.builtin.set_fact:
        root_group_members: []
        detected_users: []
      changed_when: false

    # =========================================================
    # 1. 진단: Root 그룹 멤버 확인
    # =========================================================
    - name: "U-08 | Check members of 'root' group"
      ansible.builtin.shell: |
        # getent group root 결과에서 4번째 필드(멤버) 추출
        # 결과 예: root:x:0:user1,user2 -> user1,user2
        getent group root | cut -d: -f4
      register: r_check_group
      changed_when: false
      failed_when: false

    - name: "U-08 | Parse members"
      ansible.builtin.set_fact:
        # 쉼표로 구분된 문자열을 리스트로 변환 (공백 제거)
        root_group_members: "{{ r_check_group.stdout.strip().split(',') | map('trim') | select('length', '>', 0) | list }}"
      changed_when: false

    - name: "U-08 | Identify non-root members"
      ansible.builtin.set_fact:
        # 멤버 리스트에서 'root'를 제외한 나머지 계정 식별
        detected_users: "{{ root_group_members | reject('equalto', 'root') | list }}"
      changed_when: false

    # =========================================================
    # 2. 결과 로깅 (Audit Only)
    # =========================================================
    - name: "U-08 | 조치 내용 상세 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_step
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_step.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "Root 그룹 멤버 점검 (수동 조치 필요)",
                  "cmd": "getent group root",
                  "result": "members=" ~ (root_group_members | join(", ") if (root_group_members | length > 0) else "Empty") ~
                            ", detected_unnecessary=" ~ (detected_users | join(", ") if (detected_users | length > 0) else "None")
                } | to_json
              }}
          changed_when: false

    - name: "U-08 | 최종 결과 근거 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_basis
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_basis.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    (detected_users | length > 0) | ternary(
                      "불필요 계정 발견: " ~ (detected_users | join(", ")) ~ " (수동 제거 필요)",
                      "Root 그룹에 불필요한 계정이 없음"
                    )
                  ),
                  "status": ((detected_users | length > 0) | ternary("취약(수동조치필요)", "양호"))
                } | to_json
              }}
          changed_when: false