- name: "[U_11] Remediate System Account Shells"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_11"
    category: "account"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

    # 점검 대상 계정 목록 (가이드 기준)
    target_accounts:
      - daemon
      - bin
      - sys
      - adm
      - listen
      - nobody
      - nobody4
      - noaccess
      - diag
      - operator
      - games
      - gopher

  tasks:
    # =========================================================
    # 1. [U_11_1] 불필요한 계정 쉘 제한 (/bin/false or nologin)
    # =========================================================
    - name: "[U_11_1] Block for System Account Shell Remediation"
      when: "'U_11_1' in flag_list"
      block:
        # -----------------------------------------------------
        # 실제 조치 태스크 시작
        # -----------------------------------------------------

        # 1-1. OS별 Nologin 쉘 경로 설정
        - name: "[U_11_1] Set nologin shell path based on OS"
          set_fact:
            nologin_shell: "{{ '/sbin/nologin' if ansible_os_family == 'RedHat' else '/usr/sbin/nologin' }}"

        # 1-2. 현재 시스템에 존재하는 사용자 목록 가져오기
        - name: "[U_11_1] Get all user info"
          getent:
            database: passwd

        # 1-3. 대상 계정 중 실제 존재하는 계정만 필터링하여 쉘 변경
        # 주의: user 모듈은 계정이 없으면 생성해버리므로, 반드시 존재 여부 체크 후 실행해야 함
        - name: "[U_11_1] Change shell for existing system accounts"
          user:
            name: "{{ item }}"
            shell: "{{ nologin_shell }}"
          loop: "{{ target_accounts }}"
          when: item in ansible_facts.getent_passwd
          register: r_shell_change

        # -----------------------------------------------------
        # 실제 조치 태스크 끝
        # -----------------------------------------------------

        # [성공 로그: Status 2]
        - name: "Log U_11_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_11_1",
                  "status": 2,
                  "description": "불필요한 시스템 계정의 쉘을 {{ nologin_shell }}로 변경 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_11_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_11_1",
                "section": "[조치 결과]",
                "title": "[U_11_1] 시스템 계정 쉘 제한 설정 성공",
                "cmd": "존재하는 시스템 계정에 대해 {{ nologin_shell }} 적용 완료",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_11_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_11_1",
                  "status": 0,
                  "description": "조치 실패: 계정 쉘 변경 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_11_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_11_1",
                "section": "[조치 결과]",
                "title": "[U_11_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 계정 잠금 권한 문제 또는 파일 시스템 오류 확인 필요"
              }