- name: "[U_12] Remediate Session Timeout Configuration"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_12"
    category: "account"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_12_1] bash, ksh, sh 설정 (TMOUT=600)
    # =========================================================
    - name: "[U_12_1] Configure TMOUT in /etc/profile"
      when: "'U_12_1' in flag_list"
      block:
        # 1-1. TMOUT 값 설정 (없으면 추가, 있으면 수정)
        - name: "[U_12_1] Set TMOUT=600 in /etc/profile"
          lineinfile:
            path: /etc/profile
            regexp: '^TMOUT='
            line: 'TMOUT=600'
            state: present
            create: yes
          register: r_tmout_val

        # 1-2. export TMOUT 설정
        - name: "[U_12_1] Export TMOUT in /etc/profile"
          lineinfile:
            path: /etc/profile
            regexp: '^export TMOUT'
            line: 'export TMOUT'
            state: present
            create: yes
          register: r_tmout_exp

        # 1-3. [Control Node] 로그 기록
        - name: "Log U_12_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_12_1",
                "section": "[조치 결과]",
                "title": "[U_12_1] bash/sh 세션 타임아웃 설정 성공",
                "cmd": "Update /etc/profile (TMOUT=600)",
                "result": "조치 성공 (status: 2)"
              }

        # 1-4. [Control Node] JSON 기록
        - name: "Log U_12_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_12_1",
                  "status": 2,
                  "description": "bash/sh 세션 타임아웃(TMOUT=600) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_12_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_12_1",
                  "status": 0,
                  "description": "조치 실패: /etc/profile 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_12_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_12_1",
                "section": "[조치 결과]",
                "title": "[U_12_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 권한 또는 파일 시스템 오류 확인 필요"
              }


    # =========================================================
    # 2. [U_12_2] csh 설정 (autologout=10)
    # =========================================================
    - name: "[U_12_2] Configure autologout in /etc/csh.cshrc"
      when: "'U_12_2' in flag_list"
      block:
        # 2-1. csh 설정 파일 수정
        # csh의 autologout 단위는 '분'입니다. (10분 = 600초)
        - name: "[U_12_2] Set autologout=10 in /etc/csh.cshrc"
          lineinfile:
            path: /etc/csh.cshrc
            regexp: '^set autologout='
            line: 'set autologout=10'
            state: present
            create: yes
          register: r_csh_auto

        # 2-2. [Control Node] 로그 기록
        - name: "Log U_12_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_12_2",
                "section": "[조치 결과]",
                "title": "[U_12_2] csh 세션 타임아웃 설정 성공",
                "cmd": "Update /etc/csh.cshrc (set autologout=10)",
                "result": "조치 성공 (status: 2)"
              }

        # 2-3. [Control Node] JSON 기록
        - name: "Log U_12_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_12_2",
                  "status": 2,
                  "description": "csh 세션 타임아웃(autologout=10) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_12_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_12_2",
                  "status": 0,
                  "description": "조치 실패: /etc/csh.cshrc 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_12_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_12_2",
                "section": "[조치 결과]",
                "title": "[U_12_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 경로 또는 권한 확인 필요"
              }