- name: "[U_13] Remediate Password Encryption Algorithm"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_13"
    category: "account"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname }}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [RedHat 계열] Rocky, CentOS 등 -> Log ID: U_13_1
    # =========================================================
    - name: "[U_13_1] RedHat Password Encryption Remediation"
      when: 
        - "'U_13_1' in flag_list"
        - ansible_os_family == 'RedHat'
      block:
        # 1-1. /etc/login.defs 수정
        - name: "[RedHat] Set ENCRYPT_METHOD to SHA512 in /etc/login.defs"
          lineinfile:
            path: /etc/login.defs
            regexp: '^ENCRYPT_METHOD'
            line: 'ENCRYPT_METHOD SHA512'
            state: present
          register: r_login_defs_rh

        # 1-2. /etc/pam.d/system-auth 수정
        # pam_unix.so 라인에 md5가 있다면 sha512로 변경, 없으면 sha512 추가
        - name: "[RedHat] Configure system-auth for SHA512"
          replace:
            path: /etc/pam.d/system-auth
            regexp: '(password\s+.*pam_unix\.so\s+.*)(md5)(.*)'
            replace: '\1sha512\3'
          register: r_pam_rh_replace

        # md5가 없어서 위 replace가 안 먹힌 경우, sha512가 없으면 강제 추가
        - name: "[RedHat] Ensure sha512 option in system-auth"
          lineinfile:
            path: /etc/pam.d/system-auth
            regexp: '^(password\s+.*pam_unix\.so(?!.*sha512).*)$'
            line: '\1 sha512'
            backrefs: yes
          register: r_pam_rh_ensure

        # [성공 로그: U_13_1]
        - name: "Log U_13_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_13_1",
                  "status": 2,
                  "description": "[RedHat] 패스워드 암호화 알고리즘(SHA-512) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_13_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_13_1",
                "section": "[조치 결과]",
                "title": "[RedHat] 패스워드 암호화 설정 성공",
                "cmd": "login.defs 및 system-auth(PAM)에 SHA512 적용",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: U_13_1]
      rescue:
        - name: "Log U_13_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_13_1",
                  "status": 0,
                  "description": "[RedHat] 조치 실패: PAM 설정 또는 login.defs 수정 중 에러",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_13_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_13_1",
                "section": "[조치 결과]",
                "title": "[RedHat] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }


    # =========================================================
    # 2. [Debian 계열] Ubuntu 등 -> Log ID: U_13_1
    # =========================================================
    - name: "[U_13_1] Debian Password Encryption Remediation"
      when: 
        - "'U_13_1' in flag_list"
        - ansible_os_family == 'Debian'
      block:
        # 2-1. /etc/login.defs 수정
        - name: "[Debian] Set ENCRYPT_METHOD to SHA512 in /etc/login.defs"
          lineinfile:
            path: /etc/login.defs
            regexp: '^ENCRYPT_METHOD'
            line: 'ENCRYPT_METHOD SHA512'
            state: present
          register: r_login_defs_deb

        # 2-2. /etc/pam.d/common-password 수정
        # md5나 sha256을 sha512로 교체. (Ubuntu 기본값인 yescrypt는 안전하므로 유지해도 되지만, 가이드 기준 sha512로 통일 시도)
        - name: "[Debian] Configure common-password for SHA512"
          replace:
            path: /etc/pam.d/common-password
            regexp: '(password\s+.*pam_unix\.so\s+.*)(md5|sha256)(.*)'
            replace: '\1sha512\3'
          register: r_pam_deb_replace

        # sha512나 yescrypt가 없는 경우 sha512 추가
        - name: "[Debian] Ensure sha512 in common-password if weak"
          lineinfile:
            path: /etc/pam.d/common-password
            regexp: '^(password\s+.*pam_unix\.so(?!.*(sha512|yescrypt)).*)$'
            line: '\1 sha512'
            backrefs: yes
          register: r_pam_deb_ensure

        # [성공 로그: U_13_1]
        - name: "Log U_13_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_13_1",
                  "status": 2,
                  "description": "[Debian] 패스워드 암호화 알고리즘(SHA-512) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_13_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_13_1",
                "section": "[조치 결과]",
                "title": "[Debian] 패스워드 암호화 설정 성공",
                "cmd": "login.defs 및 common-password(PAM)에 SHA512 적용",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: U_13_1]
      rescue:
        - name: "Log U_13_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_13_1",
                  "status": 0,
                  "description": "[Debian] 조치 실패: PAM 설정 또는 login.defs 수정 중 에러",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_13_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_13_1",
                "section": "[조치 결과]",
                "title": "[Debian] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }