---
- name: "U-34 | Remediate Finger Service (Rocky/Ubuntu)"
  hosts: all
  become: yes
  gather_facts: no

  vars:
    FLAG_ID: "U-34"
    # 파일 경로 정의
    inetd_conf: "/etc/inetd.conf"
    xinetd_finger_conf: "/etc/xinetd.d/finger"

    # 로그 포맷 정의
    LOG_SECTION_STEP: "[조치 내용]"
    LOG_SECTION_BASIS: "[조치 결과]"
    LOG_TITLE_BASIS: "조치 근거"
    LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"

  tasks:
    # ---------------------------------------------------------
    # (공통) 변수 기본값: 스킵/실패로 미정의 터짐 방지
    # ---------------------------------------------------------
    - name: "U-34 | init defaults"
      ansible.builtin.set_fact:
        r_inetd_comment: {}
        r_inetd_restart: {}
        r_xinetd_disable: {}
        r_xinetd_restart: {}
        r_systemd_finger: {}
      changed_when: false

    # =========================================================
    # 조치 1) inetd: /etc/inetd.conf 내 finger 라인 주석 처리
    # =========================================================
    - name: "U-34 | [U_34_1] inetd.conf 파일 존재 여부 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_341_a
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_341_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_1] inetd.conf 파일 존재 여부",
                  "cmd": "[ -f " ~ inetd_conf ~ " ]",
                  "result": "파일 존재"
                } | to_json
              }}
          changed_when: false
      when: inetd_conf is file

    - name: "U-34 | [U_34_1] inetd.conf 파일 없음 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_341_na
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_341_na.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_1] inetd.conf 파일 존재 여부",
                  "cmd": "[ -f " ~ inetd_conf ~ " ]",
                  "result": "파일 없음"
                } | to_json
              }}
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_341_na.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": "[U_34_1] inetd.conf 파일이 존재하지 않아 inetd 경로 조치 불가(해당사항 없음)",
                  "status": "info"
                } | to_json
              }}
          changed_when: false
      when: inetd_conf is not file

    - name: "U-34 | [U_34_1] inetd finger 라인 주석 처리"
      ansible.builtin.replace:
        path: "{{ inetd_conf }}"
        regexp: '^(?![[:space:]]*#)([[:space:]]*finger[[:space:]].*)$'
        replace: '# \1'
        backup: yes
      register: r_inetd_comment
      when: inetd_conf is file

    - name: "U-34 | [U_34_1] inetd replace 결과 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_341_b
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_341_b.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_1] inetd.conf 내 finger 라인 주석 처리",
                  "cmd": "replace: regexp=^(?!#)(\\s*finger\\s.*) -> '# \\1' @ " ~ inetd_conf,
                  "result": "changed=" ~ (((r_inetd_comment.changed | default(false)) | bool) | string)
                            ~ ", backup_file=" ~ (r_inetd_comment.backup_file | default("<none>"))
                } | to_json
              }}
          changed_when: false
      when: inetd_conf is file

    - name: "U-34 | [U_34_1] inetd 재시작"
      ansible.builtin.systemd:
        name: "inetd"
        state: restarted
      when: (inetd_conf is file) and ((r_inetd_comment.changed | default(false)) | bool)
      register: r_inetd_restart
      failed_when: false

    - name: "U-34 | [U_34_1] inetd 재시작 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_341_c
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_341_c.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_1] inetd 재시작",
                  "cmd": "systemd: name=inetd state=restarted (when inetd_conf changed)",
                  "result": "attempted=" ~ (((r_inetd_comment.changed | default(false)) | bool) | string)
                            ~ ", changed=" ~ (((r_inetd_restart.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false
      when: inetd_conf is file

    - name: "U-34 | [U_34_1] inetd 조치 근거 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_341_d
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_341_d.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    "[U_34_1] inetd.conf finger 라인 "
                    ~ (((r_inetd_comment.changed | default(false)) | bool)
                        | ternary("주석 처리 적용됨(조치 수행)", "이미 주석/미존재로 변경 불필요(조치 불필요)"))
                    ~ "; inetd 재시작 "
                    ~ (((r_inetd_comment.changed | default(false)) | bool)
                        | ternary("시도됨", "미시도(변경 없음)"))
                  ),
                  "status": (((r_inetd_comment.changed | default(false)) | bool) | ternary("취약", "양호"))
                } | to_json
              }}
          changed_when: false
      when: inetd_conf is file

    # =========================================================
    # 조치 2) xinetd: /etc/xinetd.d/finger disable = yes 설정
    # =========================================================
    - name: "U-34 | [U_34_2] xinetd.d/finger 파일 존재 여부 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_342_a
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_342_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_2] xinetd.d/finger 파일 존재 여부",
                  "cmd": "[ -f " ~ xinetd_finger_conf ~ " ]",
                  "result": "파일 존재"
                } | to_json
              }}
          changed_when: false
      when: xinetd_finger_conf is file

    - name: "U-34 | [U_34_2] xinetd.d/finger 파일 없음 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_342_na
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_342_na.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_2] xinetd.d/finger 파일 존재 여부",
                  "cmd": "[ -f " ~ xinetd_finger_conf ~ " ]",
                  "result": "파일 없음"
                } | to_json
              }}
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_342_na.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": "[U_34_2] /etc/xinetd.d/finger 파일이 존재하지 않아 xinetd 경로 조치 불가(해당사항 없음)",
                  "status": "info"
                } | to_json
              }}
          changed_when: false
      when: xinetd_finger_conf is not file

    - name: "U-34 | [U_34_2] disable=yes 적용"
      ansible.builtin.lineinfile:
        path: "{{ xinetd_finger_conf }}"
        regexp: '^[[:space:]]*disable[[:space:]]*='
        line: '        disable = yes'
        backup: yes
        create: no
      register: r_xinetd_disable
      when: xinetd_finger_conf is file

    - name: "U-34 | [U_34_2] xinetd disable 결과 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_342_b
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_342_b.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_2] xinetd finger 설정 disable=yes 적용",
                  "cmd": "lineinfile: regexp='^\\s*disable\\s*=' line='disable = yes' @ " ~ xinetd_finger_conf,
                  "result": "changed=" ~ (((r_xinetd_disable.changed | default(false)) | bool) | string)
                            ~ ", backup_file=" ~ (r_xinetd_disable.backup_file | default("<none>"))
                } | to_json
              }}
          changed_when: false
      when: xinetd_finger_conf is file

    - name: "U-34 | [U_34_2] xinetd 재시작"
      ansible.builtin.systemd:
        name: "xinetd"
        state: restarted
      when: (xinetd_finger_conf is file) and ((r_xinetd_disable.changed | default(false)) | bool)
      register: r_xinetd_restart
      failed_when: false

    - name: "U-34 | [U_34_2] xinetd 조치 근거 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_342_c
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_342_c.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    "[U_34_2] /etc/xinetd.d/finger disable=yes "
                    ~ (((r_xinetd_disable.changed | default(false)) | bool)
                        | ternary("설정 적용됨(조치 수행)", "이미 disable=yes 또는 변경 불필요(조치 불필요)"))
                    ~ "; xinetd 재시작 "
                    ~ (((r_xinetd_disable.changed | default(false)) | bool)
                        | ternary("시도됨", "미시도(변경 없음)"))
                  ),
                  "status": (((r_xinetd_disable.changed | default(false)) | bool) | ternary("취약", "양호"))
                } | to_json
              }}
          changed_when: false
      when: xinetd_finger_conf is file

    # =========================================================
    # 조치 3) Systemd 서비스 중지 (socket/service)
    # - finger-server, finger.socket 등
    # =========================================================
    - name: "U-34 | [U_34_3] Finger systemd 서비스 중지 및 비활성화"
      block:
        - name: "finger systemd stop"
          ansible.builtin.systemd:
            name: "finger.socket"
            state: stopped
            enabled: false
          register: r_systemd_finger
          ignore_errors: yes

        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_343_a
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_343_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_34_3] Finger 서비스(socket) 중지 및 비활성화",
                  "cmd": "systemd: name=finger.socket state=stopped enabled=false",
                  "result": "changed=" ~ (((r_systemd_finger.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_343_a.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    "[U_34_3] Finger 서비스 "
                    ~ (((r_systemd_finger.changed | default(false)) | bool)
                        | ternary("중지/비활성화 적용됨(조치 수행)", "이미 중지 상태/서비스 없음(조치 불필요)"))
                  ),
                  "status": (((r_systemd_finger.changed | default(false)) | bool) | ternary("취약", "양호"))
                } | to_json
              }}
          changed_when: false
      rescue:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_343_na
          changed_when: false

        - name: "LOG basis (info)"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_343_na.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": "[U_34_3] Finger systemd 서비스 미존재/비대상으로 조치 불가(해당사항 없음)",
                  "status": "info"
                } | to_json
              }}
          changed_when: false