---
- name: "U-35 | Remediate Anonymous Access for Shared Services"
  hosts: all
  become: yes
  gather_facts: no

  vars:
    FLAG_ID: "U-35"
    
    # Config Paths
    vsftpd_conf_rocky: "/etc/vsftpd/vsftpd.conf"
    vsftpd_conf_ubuntu: "/etc/vsftpd.conf"
    proftpd_conf: "/etc/proftpd/proftpd.conf"
    exports_conf: "/etc/exports"
    samba_conf: "/etc/samba/smb.conf"

    # Logging Vars
    LOG_SECTION_STEP: "[조치 내용]"
    LOG_SECTION_BASIS: "[조치 결과]"
    LOG_TITLE_BASIS: "조치 근거"
    LOG_TS_CMD: "date +%Y-%m-%dT%H:%M:%S%z"

  tasks:
    - name: "U-35 | init defaults"
      ansible.builtin.set_fact:
        r_ftp_user: {}
        r_anon_user: {}
        r_vsftpd_conf: {}
        r_proftpd_conf: {}
        r_nfs_conf: {}
        r_samba_conf: {}
        # Path detection vars
        target_vsftpd_conf: ""
      changed_when: false

    # ---------------------------------------------------------
    # 1. FTP 시스템 계정 제거 (ftp, anonymous)
    # ---------------------------------------------------------
    - name: "U-35 | [U_35_1] FTP 계정 제거"
      ansible.builtin.user:
        name: ftp
        state: absent
        remove: no
      register: r_ftp_user
      ignore_errors: yes

    - name: "U-35 | [U_35_1] Anonymous 계정 제거"
      ansible.builtin.user:
        name: anonymous
        state: absent
        remove: no
      register: r_anon_user
      ignore_errors: yes

    - name: "U-35 | [U_35_1] FTP/Anonymous 계정 조치 결과 LOG"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_35_1
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_35_1.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_35_1] FTP 및 Anonymous 시스템 계정 제거",
                  "cmd": "userdel ftp / userdel anonymous",
                  "result": "ftp_removed=" ~ (((r_ftp_user.changed | default(false)) | bool) | string) ~
                            ", anon_removed=" ~ (((r_anon_user.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false
      when: (r_ftp_user.changed or r_anon_user.changed)

    # ---------------------------------------------------------
    # 2. vsFTPd 익명 접근 비활성화
    # ---------------------------------------------------------
    - name: "U-35 | Detect vsftpd config path"
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - "{{ vsftpd_conf_rocky }}"
        - "{{ vsftpd_conf_ubuntu }}"
      register: vsftpd_paths

    - name: "U-35 | Set target vsftpd config"
      ansible.builtin.set_fact:
        target_vsftpd_conf: "{{ item.stat.path }}"
      when: item.stat.exists
      loop: "{{ vsftpd_paths.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: "U-35 | [U_35_2] vsftpd.conf anonymous_enable=NO 설정"
      ansible.builtin.replace:
        path: "{{ target_vsftpd_conf }}"
        regexp: '^[[:space:]]*anonymous_enable[[:space:]]*=[[:space:]]*YES'
        replace: 'anonymous_enable=NO'
      register: r_vsftpd_conf
      when: target_vsftpd_conf != ""

    - name: "U-35 | [U_35_2] vsFTPd 재시작"
      ansible.builtin.systemd:
        name: vsftpd
        state: restarted
      when: (target_vsftpd_conf != "") and r_vsftpd_conf.changed
      ignore_errors: yes

    - name: "U-35 | [U_35_2] vsFTPd 조치 로그"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_35_2
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_35_2.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_35_2] vsFTPd 익명 접근 비활성화",
                  "cmd": "replace: anonymous_enable=YES -> NO",
                  "result": "changed=" ~ (((r_vsftpd_conf.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false
      when: target_vsftpd_conf != ""

    # ---------------------------------------------------------
    # 3. ProFTPd 익명 접근 비활성화
    # ---------------------------------------------------------
    - name: "U-35 | [U_35_3] ProFTPd Anonymous 블록 주석 처리 (Tag Commenting)"
      ansible.builtin.replace:
        path: "{{ proftpd_conf }}"
        regexp: '(?i)(<Anonymous[^>]*>)|(</Anonymous>)'
        replace: '# \1'
      register: r_proftpd_conf
      ignore_errors: yes # 파일 없으면 무시

    - name: "U-35 | [U_35_3] ProFTPd 재시작"
      ansible.builtin.systemd:
        name: proftpd
        state: restarted
      when: r_proftpd_conf.changed
      ignore_errors: yes

    - name: "U-35 | [U_35_3] ProFTPd 조치 로그"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_35_3
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_35_3.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_35_3] ProFTPd Anonymous 태그 주석 처리",
                  "cmd": "replace: <Anonymous> -> # <Anonymous>",
                  "result": "changed=" ~ (((r_proftpd_conf.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false
      when: r_proftpd_conf.changed

    # ---------------------------------------------------------
    # 4. NFS 익명 접근(anonuid, anongid) 제거
    # ---------------------------------------------------------
    - name: "U-35 | [U_35_4] NFS /etc/exports 내 anonuid/anongid 옵션 제거"
      ansible.builtin.replace:
        path: "{{ exports_conf }}"
        regexp: '(,?\s*anonuid=[^,)]+)|(,?\s*anongid=[^,)]+)'
        replace: ''
      register: r_nfs_conf
      ignore_errors: yes

    - name: "U-35 | [U_35_4] NFS 설정 재적용 (exportfs -ra)"
      ansible.builtin.command: "exportfs -ra"
      when: r_nfs_conf.changed
      ignore_errors: yes

    - name: "U-35 | [U_35_4] NFS 조치 로그"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_35_4
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_35_4.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_35_4] NFS anonuid/anongid 옵션 제거",
                  "cmd": "replace: anonuid/anongid -> empty",
                  "result": "changed=" ~ (((r_nfs_conf.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false
      when: r_nfs_conf.changed

    # ---------------------------------------------------------
    # 5. Samba 익명 접근(guest ok) 비활성화
    # ---------------------------------------------------------
    - name: "U-35 | [U_35_5] Samba guest ok = no 설정"
      ansible.builtin.replace:
        path: "{{ samba_conf }}"
        regexp: '^[[:space:]]*guest[[:space:]]+ok[[:space:]]*=[[:space:]]*yes'
        replace: '   guest ok = no'
      register: r_samba_conf
      ignore_errors: yes

    - name: "U-35 | [U_35_5] Samba 재시작"
      # Rocky: smb, Ubuntu: smbd (try generic restart or ignore error)
      ansible.builtin.shell: "systemctl restart smb || systemctl restart smbd"
      when: r_samba_conf.changed
      ignore_errors: yes

    - name: "U-35 | [U_35_5] Samba 조치 로그"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_35_5
          changed_when: false

        - name: "LOG step"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_35_5.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_STEP,
                  "title": "[U_35_5] Samba guest ok=yes 제거",
                  "cmd": "replace: guest ok=yes -> guest ok=no",
                  "result": "changed=" ~ (((r_samba_conf.changed | default(false)) | bool) | string)
                } | to_json
              }}
          changed_when: false
      when: r_samba_conf.changed

    # ---------------------------------------------------------
    # Final Basis Log (종합 결과)
    # ---------------------------------------------------------
    - name: "U-35 | Final Basis Log"
      block:
        - name: "ts"
          ansible.builtin.command: "{{ LOG_TS_CMD }}"
          register: ts_35_final
          changed_when: false

        - name: "LOG basis"
          ansible.builtin.debug:
            msg: >-
              {{
                {
                  "ts": (ts_35_final.stdout | default("")),
                  "flag_id": FLAG_ID,
                  "section": LOG_SECTION_BASIS,
                  "title": LOG_TITLE_BASIS,
                  "basis": (
                    "익명 접근 계정/설정 점검 결과: "
                    ~ (((r_ftp_user.changed or r_anon_user.changed) | bool) | ternary("계정 삭제됨, ", "계정 양호, "))
                    ~ (((r_vsftpd_conf.changed) | bool) | ternary("vsFTPd 설정됨, ", "vsFTPd 양호/미존재, "))
                    ~ (((r_proftpd_conf.changed) | bool) | ternary("ProFTPd 설정됨, ", "ProFTPd 양호/미존재, "))
                    ~ (((r_nfs_conf.changed) | bool) | ternary("NFS 설정됨, ", "NFS 양호/미존재, "))
                    ~ (((r_samba_conf.changed) | bool) | ternary("Samba 설정됨", "Samba 양호/미존재"))
                  ),
                  "status": (
                      ((r_ftp_user.changed or r_anon_user.changed or r_vsftpd_conf.changed or r_proftpd_conf.changed or r_nfs_conf.changed or r_samba_conf.changed) | bool)
                      | ternary("취약(조치됨)", "양호")
                  )
                } | to_json
              }}
          changed_when: false