- name: "[U_37] Remediate Crontab and At File Permissions"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_37"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_37_1] Cron 관련 권한 조치
    # - 대상: /usr/bin/crontab (750), /etc/cron.*, /var/spool/cron (640, root)
    # =========================================================
    - name: "[U_37_1] Remediate Cron permissions"
      when: "'U_37_1' in flag_list"
      block:
        # 1-1. crontab 명령어 권한 변경 (SUID 제거, 750)
        - name: "[U_37_1] Set /usr/bin/crontab permission to 0750"
          file:
            path: /usr/bin/crontab
            owner: root
            mode: '0750'
          ignore_errors: yes

        # 1-2. Cron 설정 파일 및 디렉터리 권한 변경 (640)
        # 존재하지 않는 파일은 건너뛰도록 loop와 stat 조합 또는 file 모듈의 특성 활용
        # 여기서는 명시된 파일들에 대해 존재하는 경우만 권한 수정
        - name: "[U_37_1] Set cron config files permissions to 0640"
          file:
            path: "{{ item }}"
            owner: root
            mode: '0640'
          with_items:
            - /etc/crontab
            - /etc/cron.allow
            - /etc/cron.deny
            - /var/spool/cron
          ignore_errors: yes

        # 1-3. Cron 디렉터리 내부 파일 일괄 변경 (재귀)
        # /etc/cron.d, daily 등은 실행 권한이 필요할 수 있으므로 파일만 대상으로 0640 또는 0700 설정
        # 가이드 기준: "관련 파일 권한 640 이하"
        - name: "[U_37_1] Secure cron directories"
          shell: |
            find /etc/cron.d /etc/cron.daily /etc/cron.hourly /etc/cron.monthly /etc/cron.weekly -type f -exec chmod 640 {} \; -exec chown root {} \;
          ignore_errors: yes

        # 로그 기록
        - name: "Log U_37_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_37_1",
                "section": "[조치 결과]",
                "title": "[U_37_1] Cron 관련 파일 권한 조치 성공",
                "cmd": "chmod 750 /usr/bin/crontab & chmod 640 /etc/cron*",
                "result": "조치 성공 (status: 2)"
              }

        - name: "Log U_37_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_37_1",
                  "status": 2,
                  "description": "crontab 명령어 및 설정 파일 권한 강화(750/640) 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      rescue:
        - name: "Log U_37_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_37_1",
                  "status": 0,
                  "description": "조치 실패: Cron 파일 권한 변경 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_37_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_37_1",
                "section": "[조치 결과]",
                "title": "[U_37_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }


    # =========================================================
    # 2. [U_37_2] At 관련 권한 조치
    # - 대상: /usr/bin/at (750), /etc/at.*, /var/spool/at (640, root)
    # =========================================================
    - name: "[U_37_2] Remediate At permissions"
      when: "'U_37_2' in flag_list"
      block:
        # 2-1. at 명령어 권한 변경 (SUID 제거, 750)
        - name: "[U_37_2] Set /usr/bin/at permission to 0750"
          file:
            path: /usr/bin/at
            owner: root
            mode: '0750'
          ignore_errors: yes

        # 2-2. At 설정 파일 및 스풀 디렉터리 권한 변경 (640)
        - name: "[U_37_2] Set at config files permissions to 0640"
          file:
            path: "{{ item }}"
            owner: root
            mode: '0640'
          with_items:
            - /etc/at.allow
            - /etc/at.deny
            - /var/spool/at
            - /var/spool/cron/atjobs
          ignore_errors: yes

        # 로그 기록
        - name: "Log U_37_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_37_2",
                "section": "[조치 결과]",
                "title": "[U_37_2] At 관련 파일 권한 조치 성공",
                "cmd": "chmod 750 /usr/bin/at & chmod 640 /etc/at*",
                "result": "조치 성공 (status: 2)"
              }

        - name: "Log U_37_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_37_2",
                  "status": 2,
                  "description": "at 명령어 및 설정 파일 권한 강화(750/640) 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      rescue:
        - name: "Log U_37_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_37_2",
                  "status": 0,
                  "description": "조치 실패: At 파일 권한 변경 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_37_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_37_2",
                "section": "[조치 결과]",
                "title": "[U_37_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }