- name: "[U_38] Disable DoS Vulnerable Services"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_38"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

    # 조치 대상 서비스 목록 (가이드라인 Step 기준)
    dos_services:
      - echo
      - discard
      - daytime
      - chargen
      - echo-udp
      - discard-udp
      - daytime-udp
      - chargen-udp

  tasks:
    # =========================================================
    # 1. [U_38_1] inetd.conf 설정 조치
    # =========================================================
    - name: "[U_38_1] Disable services in /etc/inetd.conf"
      when: "'U_38_1' in flag_list"
      block:
        # 1-1. 설정 파일 수정 (대상 서비스 주석 처리)
        - name: "[U_38_1] Comment out services in inetd.conf"
          replace:
            path: /etc/inetd.conf
            regexp: '^([[:space:]]*({{ dos_services | join("|") }})[[:space:]].*)$'
            replace: '# \1'
          register: r_inetd_dos

        # 1-2. inetd 서비스 재시작
        - name: "[U_38_1] Restart inetd service"
          service:
            name: inetd
            state: restarted
          when: r_inetd_dos.changed
          ignore_errors: yes

        # 1-3. [Control Node] 로그 기록
        - name: "Log U_38_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_38_1",
                "section": "[조치 결과]",
                "title": "[U_38_1] inetd.conf 내 DoS 취약 서비스 비활성화 성공",
                "cmd": "Comment out echo/discard/daytime/chargen in /etc/inetd.conf",
                "result": "조치 성공 (status: 2)"
              }

        # 1-4. [Control Node] JSON 기록
        - name: "Log U_38_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_38_1",
                  "status": 2,
                  "description": "inetd.conf 파일 내 취약 서비스 주석 처리 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_38_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_38_1",
                  "status": 0,
                  "description": "조치 실패: inetd.conf 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_38_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_38_1",
                "section": "[조치 결과]",
                "title": "[U_38_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 존재 여부 확인 필요"
              }


    # =========================================================
    # 2. [U_38_2] xinetd 설정 조치
    # =========================================================
    - name: "[U_38_2] Disable services in xinetd"
      when: "'U_38_2' in flag_list"
      block:
        # 2-1. xinetd 서비스 파일 확인
        - name: "[U_38_2] Check xinetd service files"
          stat:
            path: "/etc/xinetd.d/{{ item }}"
          loop: "{{ dos_services }}"
          register: r_xinetd_files

        # 2-2. 존재하는 파일에 대해 disable = yes 설정
        - name: "[U_38_2] Set disable=yes for existing files"
          lineinfile:
            path: "{{ item.stat.path }}"
            regexp: '^[[:space:]]*disable[[:space:]]*='
            line: '        disable = yes'
            state: present
          loop: "{{ r_xinetd_files.results }}"
          when: item.stat.exists
          register: r_xinetd_dos

        # 2-3. xinetd 서비스 재시작
        - name: "[U_38_2] Restart xinetd service"
          service:
            name: xinetd
            state: restarted
          when: r_xinetd_dos.changed
          ignore_errors: yes

        # 2-4. [Control Node] 로그 기록
        - name: "Log U_38_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_38_2",
                "section": "[조치 결과]",
                "title": "[U_38_2] xinetd 취약 서비스 비활성화 성공",
                "cmd": "Update /etc/xinetd.d/* (disable = yes)",
                "result": "조치 성공 (status: 2)"
              }

        # 2-5. [Control Node] JSON 기록
        - name: "Log U_38_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_38_2",
                  "status": 2,
                  "description": "xinetd 취약 서비스 설정 변경(disable=yes) 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_38_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_38_2",
                  "status": 0,
                  "description": "조치 실패: xinetd 설정 파일 수정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_38_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_38_2",
                "section": "[조치 결과]",
                "title": "[U_38_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 권한 확인 필요"
              }


    # =========================================================
    # 3. [U_38_3] Systemd 서비스 중지 (U_38_4 포트 점검 포함)
    # =========================================================
    - name: "[U_38_3] Stop DoS Systemd Services"
      # U_38_4(포트 점검)에서 걸린 경우도 서비스가 돌고 있다는 뜻이므로 함께 조치
      when: "'U_38_3' in flag_list or 'U_38_4' in flag_list"
      block:
        # 3-1. 서비스 중지 및 비활성화
        - name: "[U_38_3] Stop DoS services"
          service:
            name: "{{ item }}"
            state: stopped
            enabled: no
          # 서비스 이름과 소켓 이름을 모두 포함
          loop:
            - echo
            - discard
            - daytime
            - chargen
            - echo.socket
            - discard.socket
            - daytime.socket
            - chargen.socket
          ignore_errors: yes

        # 3-2. [Control Node] 로그 기록
        - name: "Log U_38_3 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_38_3",
                "section": "[조치 결과]",
                "title": "[U_38_3] DoS 취약 Systemd 서비스 중지 성공",
                "cmd": "systemctl stop/disable echo, discard, daytime, chargen",
                "result": "조치 성공 (status: 2)"
              }

        # 3-3. [Control Node] JSON 기록
        - name: "Log U_38_3 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_38_3",
                  "status": 2,
                  "description": "DoS 취약 Systemd 서비스 중지 및 비활성화 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_38_3 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_38_3",
                  "status": 0,
                  "description": "조치 실패: 서비스 중지 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_38_3 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_38_3",
                "section": "[조치 결과]",
                "title": "[U_38_3] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }