- name: "[U_39] Disable Unnecessary NFS Services"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_39"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_39] NFS 서비스 중지 및 비활성화 (통합 조치)
    # =========================================================
    - name: "[U_39] Disable NFS Services"
      # 진단 플래그 중 하나라도 켜져 있으면 조치 실행
      when: "'U_39_1' in flag_list or 'U_39_2' in flag_list or 'U_39_3' in flag_list"
      block:
        # 1-1. 서비스 중지 (OS별 서비스명 분기)
        - name: "[U_39] Define NFS services list"
          set_fact:
            nfs_services: >-
              {{
                ['nfs-server', 'rpcbind', 'nfs-mountd', 'nfs-idmapd'] if ansible_os_family == 'RedHat'
                else ['nfs-kernel-server', 'rpcbind', 'nfs-common']
              }}

        - name: "[U_39] Stop and Disable NFS services"
          service:
            name: "{{ item }}"
            state: stopped
            enabled: no
          loop: "{{ nfs_services }}"
          ignore_errors: yes
          register: r_nfs_stop

        # 1-2. [Control Node] 로그 기록
        - name: "Log U_39 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_39",
                "section": "[조치 결과]",
                "title": "[U_39] NFS 서비스 중지 및 비활성화 성공",
                "cmd": "systemctl stop/disable {{ nfs_services | join(', ') }}",
                "result": "조치 성공 (status: 2)"
              }

        # 1-3. [Control Node] JSON 기록
        - name: "Log U_39 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_39",
                  "status": 2,
                  "description": "NFS 관련 서비스(nfs-server/rpcbind) 비활성화 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_39 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_39",
                  "status": 0,
                  "description": "조치 실패: NFS 서비스 중지 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_39 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_39",
                "section": "[조치 결과]",
                "title": "[U_39] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - systemctl 권한 또는 서비스명 확인 필요"
              }