- name: "[U_40] Remediate NFS Access Control"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_40"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

  tasks:
    # =========================================================
    # 1. [U_40_1] /etc/exports 파일 권한 조치 (644, root)
    # =========================================================
    - name: "[U_40_1] Secure /etc/exports permissions"
      when: "'U_40_1' in flag_list"
      block:
        # 1-1. 파일 존재 여부 확인
        - name: "[U_40_1] Check if /etc/exports exists"
          stat:
            path: /etc/exports
          register: st_exports

        # 1-2. 권한 및 소유자 변경
        - name: "[U_40_1] Set /etc/exports owner=root mode=0644"
          file:
            path: /etc/exports
            owner: root
            mode: '0644'
          when: st_exports.stat.exists
          register: r_exports_perm

        # 1-3. [Control Node] 로그 기록
        - name: "Log U_40_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_40_1",
                "section": "[조치 결과]",
                "title": "[U_40_1] NFS 설정 파일 권한 조치 성공",
                "cmd": "chown root /etc/exports && chmod 644 /etc/exports",
                "result": "조치 성공 (status: 2)"
              }

        # 1-4. [Control Node] JSON 기록
        - name: "Log U_40_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_40_1",
                  "status": 2,
                  "description": "/etc/exports 권한(644) 및 소유자(root) 설정 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_40_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_40_1",
                  "status": 0,
                  "description": "조치 실패: 파일 권한 변경 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_40_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_40_1",
                "section": "[조치 결과]",
                "title": "[U_40_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 파일 존재 여부 확인 필요"
              }


    # =========================================================
    # 2. [U_40_2] /etc/exports 접근 설정 점검 (수동 조치 필요)
    # =========================================================
    - name: "[U_40_2] Audit NFS Access Control (Manual Action Required)"
      when: "'U_40_2' in flag_list"
      block:
        # 2-1. 취약한 설정 검색 (* 와일드카드, insecure, no_root_squash 등)
        - name: "[U_40_2] Check for insecure NFS options"
          shell: "grep -v '^#' /etc/exports | grep -E '\\*|insecure|no_root_squash'"
          register: r_nfs_audit
          changed_when: false
          failed_when: false

        # 2-2. 취약점 발견 시 로그 기록 (자동 조치 불가 알림)
        - name: "[U_40_2] Log Failure (Manual Action Required)"
          when: r_nfs_audit.stdout_lines | length > 0
          block:
            - name: "Log U_40_2 Failure (JSON)"
              delegate_to: localhost
              become: false
              ansible.builtin.lineinfile:
                path: "{{ my_json_file }}"
                create: yes
                mode: '0644'
                line: >-
                  {
                    "meta": {
                      "hostname": "{{ ansible_hostname }}",
                      "ip": "{{ ansible_default_ipv4.address }}",
                      "user": "{{ ansible_user_id }}"
                    },
                    "result": {
                      "flag_id": "U_40_2",
                      "status": 0,
                      "description": "조치 불가: NFS 접근 설정에 와일드카드(*) 등이 포함됨. 수동 수정 필요.",
                      "category": "{{ category }}",
                      "timestamp": "{{ ts_stdout }}"
                    }
                  }

            - name: "Log U_40_2 Failure (Log File)"
              delegate_to: localhost
              become: false
              ansible.builtin.lineinfile:
                path: "{{ my_log_file }}"
                create: yes
                mode: '0644'
                line: >-
                  {
                    "ts": "{{ ts_stderr }}",
                    "flag_id": "U_40_2",
                    "section": "[조치 결과]",
                    "title": "[U_40_2] 자동 조치 불가 (수동 확인 필요)",
                    "cmd": "발견된 취약 설정: {{ r_nfs_audit.stdout | replace('\n', ' / ') }}",
                    "result": "조치 실패 (status: 0) - 허용할 호스트 IP를 알 수 없어 자동 수정 불가"
                  }

        # 2-3. (드물지만) 취약점이 없는데 플래그가 켜진 경우 (오탐 가능성 등)
        - name: "[U_40_2] Log Success (Safe)"
          when: r_nfs_audit.stdout_lines | length == 0
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_40_2",
                  "status": 2,
                  "description": "양호: NFS 접근 설정에 명백한 취약점이 발견되지 않음",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }