- name: "[U_41] Disable Automountd Service"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_41"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙 (호스트네임에서 -scan 제거 적용)
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '') }}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '') }}-remediate_{{ flag_id_main }}.json"

    # 서비스 명 정의 (대부분의 리눅스 배포판에서 autofs 사용)
    service_name: "autofs"

  tasks:
    # =========================================================
    # 1. [U_41_1] 서비스 실행 상태(Active)에 대한 조치
    # =========================================================
    - name: "[U_41_1] Stop Autofs Service (Running)"
      when: "'U_41_1' in flag_list"
      block:
        - name: "[U_41_1] Stop autofs service"
          service:
            name: "{{ service_name }}"
            state: stopped
          register: r_autofs_stop
          ignore_errors: yes

        # 로그 기록
        - name: "Log U_41_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_41_1",
                "section": "[조치 결과]",
                "title": "[U_41_1] 실행 중인 autofs 서비스 중지 성공",
                "cmd": "systemctl stop {{ service_name }}",
                "result": "조치 성공 (status: 2)"
              }

        - name: "Log U_41_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_41_1",
                  "status": 2,
                  "description": "실행 중인 automountd(autofs) 서비스 중지 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      rescue:
        - name: "Log U_41_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_41_1",
                  "status": 0,
                  "description": "조치 실패: autofs 서비스 중지 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_41_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_41_1",
                "section": "[조치 결과]",
                "title": "[U_41_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }

    # =========================================================
    # 2. [U_41_2] 부팅 시 자동 실행 설정(Enable)에 대한 조치
    # =========================================================
    - name: "[U_41_2] Disable Autofs Service (Enabled at Boot)"
      when: "'U_41_2' in flag_list"
      block:
        - name: "[U_41_2] Disable autofs service"
          service:
            name: "{{ service_name }}"
            enabled: no
          register: r_autofs_disable
          ignore_errors: yes

        # 로그 기록
        - name: "Log U_41_2 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_41_2",
                "section": "[조치 결과]",
                "title": "[U_41_2] autofs 서비스 자동 실행 비활성화 성공",
                "cmd": "systemctl disable {{ service_name }}",
                "result": "조치 성공 (status: 2)"
              }

        - name: "Log U_41_2 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_41_2",
                  "status": 2,
                  "description": "automountd(autofs) 부팅 시 자동 실행 설정 해제 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

      rescue:
        - name: "Log U_41_2 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_41_2",
                  "status": 0,
                  "description": "조치 실패: autofs 서비스 비활성화 설정 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_41_2 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_41_2",
                "section": "[조치 결과]",
                "title": "[U_41_2] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0)"
              }