- name: "[U_43] Disable Unnecessary NIS Services"
  hosts: all
  become: yes
  vars:
    # 1. Flag List (Control Node에서 주입됨)
    flag_list: []
    flag_id_main: "U_43"
    category: "service"

    # 2. 타임스탬프 정의
    ts_stderr: "{{ ansible_date_time.iso8601 }}"
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}"

    # 3. 로그 파일 경로 정의 (Control Node의 경로)
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"
    
    # 파일명 규칙
    my_log_file: "{{ log_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.log"
    my_json_file: "{{ json_dir }}/{{ ansible_hostname | replace('-scan', '')}}-remediate_{{ flag_id_main }}.json"

    # 차단 대상 NIS 서비스 목록 (가이드 및 진단 스크립트 기준)
    nis_services:
      - ypserv
      - ypbind
      - ypxfrd
      - rpc.yppasswdd
      - rpc.ypupdated
      - yppasswdd
      - ypupdated
      - nis-domainname

  tasks:
    # =========================================================
    # 1. [U_43_1] NIS 서비스 중지 및 비활성화 (통합 조치)
    # =========================================================
    - name: "[U_43_1] Block for NIS Services Remediation"
      when: "'U_43_1' in flag_list"
      block:
        # -----------------------------------------------------
        # 실제 조치 태스크 시작
        # -----------------------------------------------------
        - name: "[U_43_1] Stop and Disable NIS services"
          service:
            name: "{{ item }}"
            state: stopped
            enabled: no
          loop: "{{ nis_services }}"
          ignore_errors: yes
          register: r_nis_stop

        # -----------------------------------------------------
        # 실제 조치 태스크 끝
        # -----------------------------------------------------

        # [성공 로그: Status 2]
        - name: "Log U_43_1 Success (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_43_1",
                  "status": 2,
                  "description": "NIS 관련 서비스(ypserv, ypbind 등) 비활성화 완료",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_43_1 Success (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_43_1",
                "section": "[조치 결과]",
                "title": "[U_43_1] NIS 서비스 중지 및 비활성화 성공",
                "cmd": "systemctl stop/disable ypserv, ypbind, ypxfrd 등",
                "result": "조치 성공 (status: 2)"
              }

      # [실패 처리: Status 0]
      rescue:
        - name: "Log U_43_1 Failure (JSON)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_json_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "meta": {
                  "hostname": "{{ ansible_hostname }}",
                  "ip": "{{ ansible_default_ipv4.address }}",
                  "user": "{{ ansible_user_id }}"
                },
                "result": {
                  "flag_id": "U_43_1",
                  "status": 0,
                  "description": "조치 실패: NIS 서비스 제어 중 에러 발생",
                  "category": "{{ category }}",
                  "timestamp": "{{ ts_stdout }}"
                }
              }

        - name: "Log U_43_1 Failure (Log File)"
          delegate_to: localhost
          become: false
          ansible.builtin.lineinfile:
            path: "{{ my_log_file }}"
            create: yes
            mode: '0644'
            line: >-
              {
                "ts": "{{ ts_stderr }}",
                "flag_id": "U_43_1",
                "section": "[조치 결과]",
                "title": "[U_43_1] 조치 실패",
                "cmd": "Ansible Task Failed",
                "result": "조치 실패 (status: 0) - 서비스명 확인 또는 권한 문제 가능성"
              }