---
- name: 주요정보통신기반시설 보안 조치 - U-15 (소유자가 존재하지 않는 파일 및 디렉터리 존재 여부 점검)
  hosts: all
  become: yes

  vars:
  # 예시를 위해 DB에서 받은 데이터를 가정 (실제로는 postgres_query 등으로 받음)
  # db_result.query_result[0].val 값이 '123'(숫자형 문자열)인지 'abc'(문자열)인지에 따라 분기

    target_owner: "root"
    target_group: "root"
    ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
    STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료
    flag_list: []
    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
    my_log_file: "{{ log_dir }}/ubuntu24-remediate"
    my_json_file: "{{ json_dir }}/ubuntu24-remediate"
  tasks: 
   - name: "소유자나 그룹이 존재하지 않는 파일 및 디렉터리 확인"
      # 가이드의 find 명령어를 사용하여 소유자(-nouser) 또는 그룹(-nogroup)이 없는 대상 검색
     ansible.builtin.shell: |
      find / \( -nouser -o -nogroup \) -xdev -ls 2>/dev/null
     register: orphan_files
     failed_when: false
     changed_when: false

   - name: " 소유자가 존재하지 않는 파일 또는 디렉터리 제거"
     file:
      path: "{{item}}"
      state: absent
      owner: "{{ target_owner }}"
      group: "{{ target_group }}"
     loop: "{{ orphan_files.stdout_lines }}"

   - name: "stderr"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_15_1.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_15_1",
          "section": "[조치 내용]",
          "title": "[U_15_1] (소유자가 존재하지 않는 파일 또는 디렉터리 제거)",
          "cmd": " rm <file> | <directory>",
          "result": "조치 성공 (소유자가 존재하지 않는 파일 및 디렉터리를 제거)"
         } |        to_json(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)
        }}
     when: "'U_15_1' in flag_list"
     

   - name: " 사용중이라 제거되지 않은 발견된 파일의 소유권 변경"
      # 이미지의 '조치 방법'에 따라 소유자 및 그룹을 변경함
      # (실제 환경에 따라 제거(rm)가 필요할 경우 file 모듈의 state: absent 사용)
     file:
       path: "{{ item.split()[-1] }}"
       owner: "{{ target_owner }}"
       group: "{{ target_group }}"
     loop: "{{ orphan_files.stdout_lines }}"
     
   - name: "STDERR"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_15_1.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
         {{
          {
           "ts": ts_stderr,
           "flag_id": "U_15_1",
           "section": "[조치 내용]",
           "title": "[U_15_1] (사용중이라 제거되지 않은 발견된 파일의 소유권 변경)",
           "cmd": " chown <사용자 이름> <파일 및 디렉터리 이름> chgrp <그룹 이름> <파일 및 디렉터리 이름>",
           "result": "조치 성공 (사용중이라 제거되지 않은 발견된 파일의 소유권 변경)"
          } |        to_json(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)
         }}
     when: "'U_15_1' in flag_list"

   - name: "SYSOUT"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
        path: "{{ my_json_file }}_U_15_1.json"     # [필수] vars에 선언한 로그 파일 경로
        create: yes                   # [옵션] 파일 없으면 생성
        mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
        line: >-
          {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_15_1",
              "status": 2, 
              "description": "파일 및 디렉터리의 소유자 설정 완료",
              "category": "file",
              "timestamp": ts_stdout
             }
           } |       to_json(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)(ensure_ascii=False)
          }}
     changed_when: false
     when: "'U_15_1' in flag_list"
   
     