---
- name: 주요정보통신기반시설 보안 조치 - U-21 ( /etc/(r)syslog.conf 파일 권한 적절성 여부 점검 )
  hosts: all
  become: yes


  vars:
    # 리스트 형식(-)으로 정확히 정의해야 합니다.
   target_files:
      - /etc/syslog.conf
      - /etc/rsyslog.conf
   flag_list: []
   file: "file"
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: {{ansible_hostname| replace('-scan','')}}-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/{{ansible_hostname| replace('-scan','')}}-remediate"
   my_json_file: "{{ json_dir }}/{{ansible_hostname| replace('-scan','')}}-remediate"
  tasks: 
   - name: "/etc/(r)syslog.conf 파일 상태 확인"
     ansible.builtin.stat:
       path: "{{ item }}"
     loop: "{{ target_files }}"
     register: syslog_stats

   - name: "파일이 존재할 때만 권한 변경"
     ansible.builtin.file:
       path: "{{ item.item }}"
       owner: root
       group: root
       mode: '0640'
     loop: "{{ syslog_stats.results }}"
     # 파일이 실제로 존재할 때만 실행하여 에러 방지
     when: item.stat.exists

   - name: "STDERR"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_21.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
         "ts": ts_stderr,
         "flag_id": "U_21_1",
         "section": "[조치 내용]",
         "title": "[U_21_1] (/etc/(r)syslog.conf 권한 변경)",
         "cmd": " chown root /etc/(r)syslog.conf, chmod 640 /etc/(r)syslog.conf ",
         "result": "조치 성공 (/etc/(r)syslog.conf 권한 변경)"
        } |  to_json(ensure_ascii=False)
        }}
     when: "'U_21_1' in flag_list"

   - name: "SYSOUT"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
      path: "{{ my_json_file }}_U_21.json"     # [필수] vars에 선언한 로그 파일 경로
      create: yes                   # [옵션] 파일 없으면 생성
      mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
      line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_21_1",
              "status": 2, 
              "description": "/etc/(r)syslog.conf 권한 변경 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json(ensure_ascii=False)
        }}
     changed_when: false
     when: "'U_21_1' in flag_list"

   