---
- name: "U-24 사용자 및 시스템 환경변수 파일 권한 설정 점검"
  hosts: all
  become: yes
   

  vars:
   env_files:
      - ".profile"
      - ".kshrc"
      - ".cshrc"
      - ".bashrc"
      - ".bash_profile"
      - ".login"
      - ".exrc"
      - ".netrc"
   flag_list: []
   file: "file"
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/ubuntu24-remediate_{{ flag_list }}.log"
   my_json_file: "{{ json_dir }}/ubuntu24-remediate_{{ flag_list }}.json"
  tasks: 
    - name: "1. 시스템 내 일반 사용자 목록 추출"
      ansible.builtin.shell: "awk -F: '$3 >= 1240 {print $1\":\"$6}' /etc/passwd"
      register: user_list
      changed_when: false

    - name: "2. 사용자 데이터 정제"
      set_fact:
        refined_users: "{{ refined_users | default([]) + [{'user': item.split(':')[0], 'home': item.split(':')[1]}] }}"
      loop: "{{ user_list.stdout_lines }}"

    - name: "3. 모든 환경변수 파일의 존재 여부 확인"
      ansible.builtin.stat:
        path: "{{ item.1.home }}/{{ item.0 }}"
      register: env_file_stats
      with_nested:
        - "{{ env_files }}"
        - "{{ refined_users }}"
      loop_control:
        label: "Checking {{ item.1.user }}'s {{ item.0 }}"

    - name: "4. 파일이 존재하는 경우에만 소유자 및 권한 조치"
      ansible.builtin.file:
        path: "{{ item.item.1.home }}/{{ item.item.0 }}"
        owner: "{{ item.item.1.user }}"
        mode: 'o-w'
      loop: "{{ env_file_stats.results }}"
      loop_control:
        label: "Remediating {{ item.item.1.user }}'s {{ item.item.0 }}"
      # 핵심 수정 부분: stat 결과에서 파일이 존재(exists)할 때만 실행
      when: item.stat.exists
  
    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_24_1",
          "section": "[조치 내용]",
          "title": "[U_24_1] (사용자 및 시스템 환경변수 파일 권한 설정)",
          "cmd": " chown <root 또는 파일 소유자> <홈 디렉터리 환경변수 파일>, chmod o-w <홈 디렉터리 환경변수 파일>",
          "result": "조치 성공 (사용자 및 시스템 환경변수 파일 권한 설정)"
         } |   to_json(ensure_ascii=False)(ensure_ascii=False)
        }}
      when: "'U_24_1' in flag_list"

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
        path: "{{ my_json_file }}"     # [필수] vars에 선언한 로그 파일 경로
        create: yes                   # [옵션] 파일 없으면 생성
        mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
        line: >-
          {{
              {
               "meta": {
                "hostname": ansible_hostname,
                "ip": ansible_default_ipv4.address | default('N/A'),
                "user": ansible_user_id
               },
               "result": {
                "flag_id": "U_24_1",
                "status": 2, 
                "description": " 사용자 및 시스템 환경변수 파일 권한 설정 완료",
                "category": file,
                "timestamp": ts_stdout
               }
             } |  to_json(ensure_ascii=False)
          }}
      changed_when: false
      when: "'U_24_1' in flag_list" 