---
- name: "U-26 /dev에 존재하지 않는 device 파일 점검 및 조치"
  hosts: all
  become: yes
   

  vars:
   file: "file"
   flag_list: []
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/ubuntu24-remediate"
   my_json_file: "{{ json_dir }}/ubuntu24-remediate"
  tasks: 
    - name: "/dev 내 일반 파일(정상 디바이스가 아닌 파일) 검색"
      # 가이드 Step 1: find /dev -type f를 통해 장치 파일이 아닌 일반 파일을 찾습니다.
      # 시스템 생성 파일인 mqueue, shm은 제외합니다.
      ansible.builtin.shell: |
        find /dev -type f ! -name "mqueue" ! -name "shm" -exec ls -l {} \; 2>/dev/null
      register: invalid_dev_files
      changed_when: false

    - name: "[조치] 비정상 파일 삭제 "
      # 가이드 조치 사례: # rm <파일 이름>
      # major, minor 번호를 가지지 않는 일반 파일(type f)을 삭제합니다.
      ansible.builtin.file:
        path: "{{ item.split()[-1] }}"
        state: absent
      loop: "{{ invalid_dev_files.stdout_lines }}"
      when: invalid_dev_files.stdout_lines | length > 0
      register: rm_result

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_26_1.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_26_1",
          "section": "[조치 내용]",
          "title": "[U_26_1] ( /dev 내 일반 파일 삭제)",
          "cmd": " rm <파일 이름> ",
          "result": "조치 성공 (/dev 내 일반 파일 삭제)"
         } |   to_json(ensure_ascii=False)(ensure_ascii=False)
        }}
      when: "'U_26_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_26_1.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_26_1",
              "status": 2, 
              "description": "/dev 내 일반 파일 삭제 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
      changed_when: false
      when: "'U_26_1' in flag_list"