---
- name: 주요정보통신기반시설 보안 조치 - U-29 ( hosts.lpd 파일 소유자 및 권한 설정 )
  hosts: all
  become: yes
   

  vars:
   file: "file"
   flag_list: []
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: {{ansible_hostname| replace('-scan','')}}-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/{{ansible_hostname| replace('-scan','')}}-remediate"
   my_json_file: "{{ json_dir }}/{{ansible_hostname| replace('-scan','')}}-remediate"
  tasks: 
   - name: "/etc/hosts.lpd 파일 존재 여부 확인"
     ansible.builtin.stat:
       path: /etc/hosts.lpd
     register: lpd_stat

   - name: "파일이 존재할 경우 소유자 및 권한 변경"
     ansible.builtin.file:
        path: /etc/hosts.lpd
        owner: root
        group: root
        mode: '0600'
        state: file  # 파일이 있을 때만 속성을 변경함
     when: lpd_stat.stat.exists  # 파일이 존재할 때만 이 태스크를 실행함

   - name: "STDERR"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_29.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
         {{
         {
         "ts": ts_stderr,
         "flag_id": "U_29_1",
         "section": "[조치 내용]",
         "title": "[U_29_1] (/etc/hosts.lpd 소유자 및 권한 변경)",
         "cmd": " chown root /etc/hosts.lpd, chmod 600 /etc/hosts.lpd ",
         "result": "조치 성공 (/etc/hosts.lpd 소유자 및 권한 변경)"
         } |  to_json(ensure_ascii=False)
         }}
     when: "'U_29_1' in flag_list" 

   - name: "SYSOUT"
     delegate_to: localhost          # [필수] Controller에 저장
     become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
     ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_29.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_29_1",
              "status": 2, 
              "description": "/etc/hosts.lpd 소유자 및 권한 변경 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
     changed_when: false
     when: "'U_29_1' in flag_list"
     