---
- name: "U-32 홈 디렉터리로 지정한 디렉터리의 존재 관리"
  hosts: all
  become: yes
   

  vars:
    file: "file"
    flag_list: []
    ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
    ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
    STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

    log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
    json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
    my_log_file: "{{ log_dir }}/ubuntu24-remediate"
    my_json_file: "{{ json_dir }}/ubuntu24-remediate"
  tasks: 
    - name: "사용자별 홈 디렉토리 정보 가져오기"
      getent:
        database: passwd

    - name: "홈 디렉토리 존재 여부 확인"
      stat:
        path: "{{ item.value[4] }}"
      loop: "{{ ansible_facts.getent_passwd | dict2items }}"
      register: home_dir_stats
      when: item.value[2] | int >= 1000  # 일반 사용자만 확인

    - name: "삭제 대상 계정 확정"
      set_fact:
        # stat 결과에서 존재하지 않는(exists == false) 계정만 리스트화
        users_to_delete: "{{ home_dir_stats.results | selectattr('stat.exists', 'defined') | selectattr('stat.exists', 'equalto', false) | map(attribute='item.key') | list }}"

    - name: "홈 디렉토리가 없는 불필요한 계정 삭제"
      user:
        name: "{{ item }}"
        state: absent
        remove: yes  # 필요 시 홈 디렉토리까지 강제 삭제
      loop: "{{ users_to_delete }}"
      when: item in ansible_facts.getent_passwd

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_32_1.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_32_1",
          "section": "[조치 내용]",
          "title": "[U_32_1] (홈 디렉토리가 없는 불필요한 계정 삭제)",
          "cmd": " userdel <사용자 이름>",
          "result": "조치 성공 (홈 디렉토리가 없는 불필요한 계정 삭제)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_32_1' in flag_list" 

    - name: "사용 중인 계정의 홈 디렉토리 설정 및 생성"
      # /etc/passwd에 정의된 경로에 디렉토리가 없으면 생성합니다.
      file:
        path: "{{ item.value[4] }}" # getent_passwd의 5번째 필드가 홈 디렉토리 경로임
        state: directory
        owner: "{{ item.key }}"
        group: "{{ item.key }}"
        mode: '0700'
      loop: "{{ ansible_facts.getent_passwd | dict2items }}"
      when:
        # 삭제 대상이 아니고, 실제 로그인 쉘이 있는 일반 사용자만 대상으로 함
        - item.key not in users_to_delete
        - item.value[5] not in ['/sbin/nologin', '/usr/sbin/nologin', '/bin/false']
        - item.value[2] | int >= 1000  # 보통 UID 1000 이상이 일반 사용자

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_32_1.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_32_1",
          "section": "[조치 내용]",
          "title": "[U_32_1] (사용 중인 계정의 홈 디렉토리 설정 및 생성)",
          "cmd": " vi /etc/passwd -> example:x:1000:1000::/home/example:/bin/bash",
          "result": "조치 성공 (사용 중인 계정의 홈 디렉토리 설정 및 생성)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_32_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_32_1.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_32_1",
              "status": 2, 
              "description": " 홈 디렉토리가 없는 불필요한 계정 삭제 및 사용 중인 계정의 홈 디렉토리 설정 완료  ",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
      changed_when: false
      when: "'U_32_1' in flag_list"