---
- name: "U-48 expn, vrfy 명령어 제한 설정 (Sendmail, Postfix, Exim)"
  hosts: all
  become: yes
   

  vars:
   file: "system"
   flag_list: []
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: ubuntu24-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/ubuntu24-remediate"
   my_json_file: "{{ json_dir }}/ubuntu24-remediate"
  tasks:  
    # 1. 메일 서비스 활성화 상태 확인
    - name: "1. 메일 서비스 상태 확인"
      ansible.builtin.service_facts:
      register: services_state

    # --- [Sendmail 조치] ---
    - name: "2. [Sendmail] PrivacyOptions 설정 "
      block:
        - name: "sendmail.cf 파일 내 goaway 또는 noexpn, novrfy 설정 추가"
          ansible.builtin.replace:
            path: /etc/mail/sendmail.cf
            regexp: '^O\s+PrivacyOptions=(.*)'
            # 이미지 가이드의 goaway 옵션을 사용하여 통합 단축 설정 적용
            replace: 'O PrivacyOptions=restrictqrun, goaway'
          register: sendmail_update

        - name: "Sendmail 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: sendmail
            state: restarted
          when: sendmail_update.changed
      when: 
      - "'sendmail.service' in services_state.ansible_facts.services"
      - "'U_48_1' in flag_list"
    
    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_48_1.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_48_1",
          "section": "[조치 내용]",
          "title": "[U_48_1] ([Sendmail] PrivacyOptions 옵션 수정)",
          "cmd": " ",
          "result": "조치 성공 ([Sendmail] PrivacyOptions 옵션 수정)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_48_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_48_1.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_48_1",
              "status": 2, 
              "description": " [Sendmail] PrivacyOptions 옵션 수정 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
      changed_when: false
      when: "'U_48_1' in flag_list"
        

    # --- [Postfix 조치] ---
    - name: "3. [Postfix] vrfy 명령어 비활성화 (Step 1, 2)"
      block:
        - name: "main.cf 내 disable_vrfy_command 설정 (yes)"
          ansible.builtin.lineinfile:
            path: /etc/postfix/main.cf
            regexp: '^disable_vrfy_command\s*='
            line: "disable_vrfy_command = yes"
            state: present
          register: postfix_update

        - name: "Postfix 설정 적용 (Step 3)"
          ansible.builtin.shell: "postfix reload"
          when: postfix_update.changed
      when: 
      - "'postfix.service' in services_state.ansible_facts.services"
      - "'U_48_2' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_48_2.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_48_2",
          "section": "[조치 내용]",
          "title": "[U_48_2] (vrfy 명령어 비활성화)",
          "cmd": " /etc/postfix/main.cf 내 disable_vrfy_command = yes 수정 ",
          "result": "조치 성공 (vrfy 명령어 비활성화)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_48_2' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_48_2.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_48_2",
              "status": 2, 
              "description": "vrfy 명령어 비활성화 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
      changed_when: false
      when: "'U_48_2' in flag_list"

    # --- [Exim 조치] ---
    - name: "4. [Exim] vrfy, expn 설정 제거 (Step 1, 2)"
      block:
        - name: "Exim 설정 파일 내 vrfy/expn 허용 설정 주석 처리"
          ansible.builtin.replace:
            path: "{{ item }}"
            regexp: '^(acl_smtp_(vrfy|expn)\s*=\s*accept)'
            replace: '# \1'
          loop:
            - /etc/exim/exim.conf
            - /etc/exim4/exim4.conf
          register: exim_update
          ignore_errors: yes

        - name: "Exim 서비스 재시작 (Step 3)"
          ansible.builtin.systemd:
            name: "{{ 'exim4' if 'exim4.service' in services_state.ansible_facts.services else 'exim' }}"
            state: restarted
          when: exim_update.changed
      when: 
      - "'exim.service' in services_state.ansible_facts.services or 'exim4.service' in services_state.ansible_facts.services"
      - "'U_48_3' in flag_list"
    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_48_3.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_48_3",
          "section": "[조치 내용]",
          "title": "[U_48_3] (vrfy 명령어 비활성화)",
          "cmd": " /etc/exim(4)/exim(4).conf 내 acl_smtp_vrfy = acceptacl_smtp_expn = accept 삭제",
          "result": "조치 성공 (vrfy 명령어 비활성화)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_48_3' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_48_3.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_48_3",
              "status": 2, 
              "description": "vrfy 명령어 비활성화 완료 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } | to_json
        }}
      changed_when: false
      when: "'U_48_3' in flag_list"