---
- name: "U-52 Telnet 서비스 비활성화 및 SSH 사용 설정"
  hosts: all
  become: yes
   

  vars:
   file: "service"
   flag_list: []
   ts_stderr: "{{ ansible_date_time.iso8601 }}" # 2026-02-11T16:45:12Z
   ts_stdout: "{{ ansible_date_time.date | replace('-','_') }} / {{ ansible_date_time.time }}" # 2026_02_11 / 12:13:28
   STATUS: 0 # yaml코드 실행 성공 여부 / 0: 시작 1: 중간 2: 완료

   log_dir: "{{ isms_remediate_log_dir | default('/tmp') }}"
   json_dir: "{{ isms_remediate_json_dir | default('/tmp') }}"

    # 파일명 규칙: {{ansible_hostname| replace('-scan','')}}-remediate_U-54.log / .json
   my_log_file: "{{ log_dir }}/{{ansible_hostname| replace('-scan','')}}-remediate"
   my_json_file: "{{ json_dir }}/{{ansible_hostname| replace('-scan','')}}-remediate"
  tasks: 
    # 0. 서비스 상태 수집 (서비스 존재 여부 확인용)
    - name: "0. 시스템 서비스 정보 수집"
      ansible.builtin.service_facts:
      register: services_state

    # 1. [inetd] 환경 조치
    - name: "1. [inetd] 파일 확인 및 조치"
      block:
        - name: "1-1. /etc/inetd.conf 존재 확인"
          ansible.builtin.stat:
            path: /etc/inetd.conf
          register: inetd_file

        - name: "1-2. /etc/inetd.conf 내 Telnet 주석 처리"
          ansible.builtin.replace:
            path: /etc/inetd.conf
            regexp: '^(\s*telnet\s+.*)$'
            replace: '# \1'
          when: inetd_file.stat.exists
          register: inetd_update

        - name: "1-3. inetd 서비스 재시작"
          ansible.builtin.service:
            name: inetd
            state: restarted
          when: 
            - inetd_file.stat.exists 
            - inetd_update.changed 
            - "'inetd.service' in services_state.ansible_facts.services"
      ignore_errors: yes
      when: "'U_52_1' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_52.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_52_1",
          "section": "[조치 내용]",
          "title": "[U_52_1] (/etc/inetd.conf 내 Telnet 주석 처리)",
          "cmd": "/etc/inetd.conf-> telnet stream tcp nowait root /usr/sbin/in.telnetd 주석 처리  ",
          "result": "조치 성공 (/etc/inetd.conf 내 Telnet 주석 처리)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_52_1' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_52.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_52_1",
              "status": 2, 
              "description": " /etc/inetd.conf 내 Telnet 주석 처리 ",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
      changed_when: false
      when: "'U_52_1' in flag_list"

    # 2. [xinetd] 환경 조치
    - name: "2. [xinetd] 파일 확인 및 조치"
      block:
        - name: "2-1. /etc/xinetd.d/telnet 존재 확인"
          ansible.builtin.stat:
            path: /etc/xinetd.d/telnet
          register: xinetd_file

        - name: "2-2. /etc/xinetd.d/telnet 파일 수정"
          ansible.builtin.lineinfile:
            path: /etc/xinetd.d/telnet
            regexp: '^\s*disable\s*='
            line: "\tdisable = yes"
          when: xinetd_file.stat.exists
          register: xinetd_update

        - name: "2-3. xinetd 서비스 재시작"
          ansible.builtin.systemd:
            name: xinetd
            state: restarted
          when: 
            - xinetd_file.stat.exists 
            - xinetd_update.changed
            - "'xinetd.service' in services_state.ansible_facts.services"
      ignore_errors: yes
      when: "'U_52_2' in flag_list"

    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_52.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_52_2",
          "section": "[조치 내용]",
          "title": "[U_52_2] (/etc/xinetd.d/telnet 파일 수정)",
          "cmd": "/etc/xinetd.d/telnet  -> disable = yes",
          "result": "조치 성공 (/etc/xinetd.d/telnet 파일 수정)"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_52_2' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_52.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_52_2",
              "status": 2, 
              "description": " //etc/xinetd.d/telnet 파일 수정 완료",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
        }}
      changed_when: false
      when: "'U_52_2' in flag_list"

    # 3. [systemd] 환경 조치
    - name: "3. [systemd] Telnet 소켓 및 서비스 중지/비활성화"
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        masked: yes
      loop:
        - telnet.socket
        - telnet.service
      # 서비스가 시스템에 존재할 때만 실행
      when: 
      - "item in services_state.ansible_facts.services"
      - "'U_52_3' in flag_list"

      ignore_errors: yes
    - name: "STDERR"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_log_file }}_U_52.log"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
        {{
         {
          "ts": ts_stderr,
          "flag_id": "U_52_3",
          "section": "[조치 내용]",
          "title": "[systemd] Telnet 소켓 및 서비스 중지/비활성화 완료",
          "cmd": "/etc/systemctl [stop/enable] telnet.socket",
          "result": "[systemd] Telnet 소켓 및 서비스 중지/비활성화 완료"
         } |  to_json(ensure_ascii=False)
        }}
      when: "'U_52_3' in flag_list" 

    - name: "SYSOUT"
      delegate_to: localhost          # [필수] Controller에 저장
      become: false                   # [필수] 로컬 파일 쓰기 권한 문제 방지
      ansible.builtin.lineinfile:
       path: "{{ my_json_file }}_U_52.json"     # [필수] vars에 선언한 로그 파일 경로
       create: yes                   # [옵션] 파일 없으면 생성
       mode: '0644'                  # [옵션] 파일 권한 설정 (선택사항)
       line: >-
         {{
            {
             "meta": {
              "hostname": ansible_hostname,
              "ip": ansible_default_ipv4.address | default('N/A'),
              "user": ansible_user_id
             },
             "result": {
              "flag_id": "U_52_3",
              "status": 2, 
              "description": "[systemd] Telnet 소켓 및 서비스 중지/비활성화 완료",
              "category": file,
              "timestamp": ts_stdout
             }
           } |  to_json(ensure_ascii=False)
         }}
      changed_when: false
      when: "'U_52_3' in flag_list"
    # 4. SSH 서비스 활성화
    - name: "4. SSH 서비스 실행 및 자동 시작 설정"
      ansible.builtin.systemd:
        name: sshd
        state: started
        enabled: yes
      when: "'sshd.service' in services_state.ansible_facts.services"
      ignore_errors: yes